//! §14's example pairs: every `Exposed` row emits, and the emission is a
//! golden.
//!
//! *"The granular Installua→NSIS assembly tests should not be hand-written per
//! instruction; they should be impossible to omit."* So the example lives on
//! the overlay row, the census requires one on every `Exposed` row, and this
//! file compiles all of them into a single `.nsi` diffed by exact equality.
//!
//! One program with one section per row, rather than one program per row: the
//! section body **is** the smallest region containing the behaviour, so the
//! golden reads as a table of what each name emits and a wrong lowering shows
//! up as three changed lines rather than as a changed file.
//!
//! This is the mechanism PLAN's Phase 6 depends on. "One overlay row plus its
//! mandatory example pair" is only data entry if the *mandatory* half is
//! enforced; otherwise it is a debate about whether this one needs a test.

use installua::diag::Diagnostics;
use installua::table::{self, Class};

/// The whole exposed surface, as one installer.
fn program() -> String {
    let mut source = String::from(
        "-- Generated by tests/overlay.rs from the overlay's own examples.\n\
         attributes {\n\
         \tname = \"Overlay examples\",\n\
         \toutFile = \"examples.exe\",\n\
         \tunicode = true,\n\
         }\n\n\
         installer {\n",
    );

    for (name, example) in examples() {
        source.push_str(&format!("\tsection(\"{name}\", function()\n"));
        for line in example.lines() {
            source.push_str(&format!("\t\t{line}\n"));
        }
        source.push_str("\tend),\n");
    }

    source.push_str("}\n");
    source
}

/// One `(section name, example)` per `Exposed` row, in `-CMDHELP` order.
///
/// Keyed on the NSIS name rather than the Installua one because two rows can
/// share an Installua name — `writeReg` is `WriteRegStr` and `WriteRegDWORD` —
/// and both dispatches need their own example.
fn examples() -> Vec<(&'static str, &'static str)> {
    table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed)
        .filter_map(|row| row.example.map(|example| (row.nsis, example)))
        .collect()
}

#[test]
fn every_exposed_row_carries_an_example() {
    // §14: this is what makes "added an instruction, forgot the test"
    // unrepresentable rather than merely discouraged.
    let missing: Vec<&str> = table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed && row.example.is_none())
        .map(|row| row.nsis)
        .collect();

    assert_eq!(missing, Vec::<&str>::new());
}

#[test]
fn every_example_compiles() {
    // Separately from the golden, because a golden that has not been
    // regenerated and a program that no longer compiles fail the same test
    // otherwise, and they are different problems.
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags);

    assert!(
        built.is_some() && !diags.has_errors(),
        "{}",
        diags.render("overlay-examples.lua")
    );
}

#[test]
fn the_examples_match_their_golden() {
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags).unwrap_or_default();

    let expected = include_str!("golden/overlay-examples.nsi");
    assert_eq!(
        built, expected,
        "regenerate with:\n  cargo test --test overlay -- --ignored write_the_golden"
    );
}

/// Regenerates the golden and the source beside it. Ignored, because a test
/// that rewrites its own expectation is not a test.
#[test]
#[ignore = "regenerates tests/golden/overlay-examples.{lua,nsi}"]
fn write_the_golden() {
    let source = program();
    let mut diags = Diagnostics::new();
    let built = installua::build(&source, &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay.lua")));

    std::fs::write("tests/golden/overlay-examples.lua", source).unwrap();
    std::fs::write("tests/golden/overlay-examples.nsi", built).unwrap();
}
