//! §14's example pairs: every `Exposed` row emits, and the emission is a
//! golden.
//!
//! *"The granular Installua→NSIS assembly tests should not be hand-written per
//! instruction; they should be impossible to omit."* So the example lives on
//! the overlay row, the census requires one on every `Exposed` row, and this
//! file compiles all of them into a single `.nsi` diffed by exact equality.
//!
//! One program with one section per row, rather than one program per row: the
//! section body **is** the smallest region containing the behaviour, so the
//! golden reads as a table of what each name emits and a wrong lowering shows
//! up as three changed lines rather than as a changed file.
//!
//! This is the mechanism PLAN's Phase 6 depends on. "One overlay row plus its
//! mandatory example pair" is only data entry if the *mandatory* half is
//! enforced; otherwise it is a debate about whether this one needs a test.

use std::path::Path;
use std::process::Command;

use installua::diag::Diagnostics;
use installua::table::{self, Class};

/// The whole exposed surface, as one installer.
fn program() -> String {
    let mut source = String::from(
        "-- Generated by tests/overlay.rs from the overlay's own examples.\n\
         attributes {\n\
         \tname = \"Overlay examples\",\n\
         \toutFile = \"examples.exe\",\n\
         \tunicode = true,\n\
         }\n\n\
         installer {\n",
    );

    for (name, example) in examples() {
        source.push_str(&format!("\tsection(\"{name}\", function()\n"));
        for line in example.lines() {
            source.push_str(&format!("\t\t{line}\n"));
        }
        source.push_str("\tend),\n");
    }

    // `WriteUninstaller` with no uninstaller is *"Error: no Uninstall section
    // specified"* — a whole-script fact, not a per-line one, so no example can
    // carry it and the program has to. This is the first thing tier 3 caught,
    // and it had been in the golden since the day the row was written.
    source.push_str(
        "}\n\nuninstaller {\n\tsection(\"Uninstall\", function()\n\t\trmDir(INSTDIR)\n\tend),\n}\n",
    );
    source
}

/// One `(section name, example)` per `Exposed` row, in `-CMDHELP` order.
///
/// Keyed on the NSIS name rather than the Installua one because two rows can
/// share an Installua name — `writeReg` is `WriteRegStr` and `WriteRegDWORD` —
/// and both dispatches need their own example.
fn examples() -> Vec<(&'static str, &'static str)> {
    table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed)
        .filter_map(|row| row.example.map(|example| (row.nsis, example)))
        .collect()
}

#[test]
fn every_exposed_row_carries_an_example() {
    // §14: this is what makes "added an instruction, forgot the test"
    // unrepresentable rather than merely discouraged.
    let missing: Vec<&str> = table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed && row.example.is_none())
        .map(|row| row.nsis)
        .collect();

    assert_eq!(missing, Vec::<&str>::new());
}

#[test]
fn every_example_compiles() {
    // Separately from the golden, because a golden that has not been
    // regenerated and a program that no longer compiles fail the same test
    // otherwise, and they are different problems.
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags);

    assert!(
        built.is_some() && !diags.has_errors(),
        "{}",
        diags.render("overlay-examples.lua")
    );
}

#[test]
fn the_examples_match_their_golden() {
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags).unwrap_or_default();

    let expected = include_str!("golden/overlay-examples.nsi");
    assert_eq!(
        built, expected,
        "regenerate with:\n  cargo test --test overlay -- --ignored write_the_golden"
    );
}

/// The two things an example cannot show, because an example is one call site
/// and these differ *between* call sites.
#[test]
fn an_optional_position_is_written_only_when_something_after_it_is() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             local f = fileOpen(INSTDIR .. \"/log.txt\", \"r\")\n\
             {body}\n\
             f:close()\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    // The output is optional, so a call nobody reads writes no register. A
    // temporary here would be correct NSIS and would still enter the clobber
    // set, costing a caller a save for a value that was never wanted.
    let discarded = build("f:seek(0, \"END\")");
    assert!(
        discarded.contains("FileSeek $0 0 \"END\"\n"),
        "an unread optional output should not be emitted:\n{discarded}"
    );

    // And `mode` is optional but *precedes* the output, so reading the result
    // means writing a mode the author never named — `FileSeek $0 0 $1` is not
    // an option, NSIS reads `$1` as the mode and rejects the line.
    let filled = build("local p = f:seek(0)\ndetailPrint(\"at \" .. p)");
    assert!(
        filled.contains("FileSeek $0 0 SET $1\n"),
        "reaching the output should fill `mode`:\n{filled}"
    );

    // Same position, same row, nothing after it: not written.
    let bare = build("f:seek(0)");
    assert!(
        bare.contains("FileSeek $0 0\n"),
        "a trailing optional stays absent:\n{bare}"
    );
}

/// Tier 3, with an empty warning allowlist (§14).
///
/// The golden above answers *"did the output change?"*. Only `makensis`
/// answers *"is the output valid NSIS?"*, and the two are not the same
/// question: swap `CreateShortcut`'s link and target and the golden passes
/// forever, because it records what the compiler emits rather than what NSIS
/// accepts. Phase 6 writes a row per command from a `-CMDHELP` line somebody
/// read, so that is the failure this is here for.
///
/// Skips cleanly when there is no `makensis`, the same trade §14 makes
/// everywhere else.
#[test]
fn the_examples_assemble_under_wx() {
    let Some(makensis) = makensis() else {
        eprintln!("skipping: `makensis` is not installed");
        return;
    };

    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay-examples.lua")));

    // `File` resolves relative to the script, so the script goes where the
    // fixtures are — see tests/fixtures/README.md.
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures");
    let script = fixtures.join("assembling.nsi");
    std::fs::write(&script, &built).expect("write the script");

    let output = Command::new(&makensis)
        .arg("-WX")
        .arg(&script)
        .current_dir(&fixtures)
        .output()
        .expect("run makensis");

    let _ = std::fs::remove_file(&script);
    let _ = std::fs::remove_file(fixtures.join("examples.exe"));

    assert!(
        output.status.success(),
        // Both streams: `makensis` prints its progress to stdout and the line
        // that says why to stderr, and only one of those is the message.
        "makensis -WX rejected the overlay examples:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn makensis() -> Option<String> {
    let name = std::env::var("MAKENSIS").unwrap_or_else(|_| "makensis".to_string());
    Command::new(&name)
        .arg("-VERSION")
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|_| name)
}

/// Regenerates the golden and the source beside it. Ignored, because a test
/// that rewrites its own expectation is not a test.
#[test]
#[ignore = "regenerates tests/golden/overlay-examples.{lua,nsi}"]
fn write_the_golden() {
    let source = program();
    let mut diags = Diagnostics::new();
    let built = installua::build(&source, &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay.lua")));

    std::fs::write("tests/golden/overlay-examples.lua", source).unwrap();
    std::fs::write("tests/golden/overlay-examples.nsi", built).unwrap();
}
