//! §14's example pairs: every `Exposed` row emits, and the emission is a
//! golden.
//!
//! *"The granular Installua→NSIS assembly tests should not be hand-written per
//! instruction; they should be impossible to omit."* So the example lives on
//! the overlay row, the census requires one on every `Exposed` row, and this
//! file compiles all of them into a single `.nsi` diffed by exact equality.
//!
//! One program with one section per row, rather than one program per row: the
//! section body **is** the smallest region containing the behaviour, so the
//! golden reads as a table of what each name emits and a wrong lowering shows
//! up as three changed lines rather than as a changed file.
//!
//! This is the mechanism PLAN's Phase 6 depends on. "One overlay row plus its
//! mandatory example pair" is only data entry if the *mandatory* half is
//! enforced; otherwise it is a debate about whether this one needs a test.

use std::path::Path;
use std::process::Command;

use installua::diag::Diagnostics;
use installua::table::{self, Class};

/// The whole exposed surface, as one installer.
fn program() -> String {
    let mut source = String::from(
        "-- Generated by tests/overlay.rs from the overlay's own examples.\n\
         attributes {\n\
         \tname = \"Overlay examples\",\n\
         \toutFile = \"examples.exe\",\n\
         \tunicode = true,\n\
         }\n\n\
         installer {\n",
    );

    for (name, example) in examples() {
        source.push_str(&format!("\tsection(\"{name}\", function()\n"));
        for line in example.lines() {
            source.push_str(&format!("\t\t{line}\n"));
        }
        source.push_str("\tend),\n");
    }

    // `WriteUninstaller` with no uninstaller is *"Error: no Uninstall section
    // specified"* — a whole-script fact, not a per-line one, so no example can
    // carry it and the program has to. This is the first thing tier 3 caught,
    // and it had been in the golden since the day the row was written.
    source.push_str(
        "}\n\nuninstaller {\n\tsection(\"Uninstall\", function()\n\t\trmDir(INSTDIR)\n\tend),\n}\n",
    );
    source
}

/// One `(section name, example)` per `Exposed` row, in `-CMDHELP` order.
///
/// Keyed on the NSIS name rather than the Installua one because two rows can
/// share an Installua name — `writeReg` is `WriteRegStr` and `WriteRegDWORD` —
/// and both dispatches need their own example.
fn examples() -> Vec<(&'static str, &'static str)> {
    table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed)
        .filter_map(|row| row.example.map(|example| (row.nsis, example)))
        .collect()
}

/// Every `Attribute` row, set to a value derived from its own [`Setting`].
///
/// An attribute needs no hand-written example the way an `Exposed` row does,
/// and that is the point of batch 10: the row *is* the example, because
/// `Setting` says what the field holds and the snapshot says which keywords an
/// enum accepts. A row that lies about either produces a line `makensis`
/// rejects, which is the tier-3 half below.
fn attribute_program() -> String {
    let mut source = String::from(
        "-- Generated by tests/overlay.rs from the overlay's own `Attribute` rows.\n\
         attributes {\n",
    );

    for entry in table::table() {
        let table::Class::Attribute(holds) = entry.class else {
            continue;
        };
        let Some(field) = entry.installua else {
            continue;
        };
        // The dotted ones are `versionInfo`'s and are written through it; the
        // rest of `Handled` is hand-shaped and has no value this can guess.
        if field.contains('.') || matches!(holds, table::Setting::Handled(_)) {
            continue;
        }

        let value = match holds {
            // `Icon` and `LicenseData` open the file at compile time, so these
            // two want a real one — see tests/fixtures/README.md.
            table::Setting::Str { path: true } if field == "icon" => {
                "\"assets/icon.ico\"".to_string()
            }
            table::Setting::Str { path: true } if field == "license" => {
                "\"assets/license.txt\"".to_string()
            }
            // Two settings take a *shaped* string — `major.minor` and
            // `maj.min.bld.rev` — and [`table::Setting::Str`] says only "a
            // string". The narrowing is real and the table cannot state it, so
            // the compiler does not check it either: `peSubsysVer = "hello"`
            // reaches `makensis` and is rejected there. The values are here
            // rather than in the row because a row is not an example.
            table::Setting::Str { path: false } if field == "peSubsysVer" => "\"5.1\"".to_string(),
            table::Setting::Str { path: false } if field == "manifestMaxVersionTested" => {
                "\"10.0.19041.0\"".to_string()
            }
            table::Setting::Str { path: true } => format!("\"{field}.out\""),
            table::Setting::Str { path: false } => format!("\"{field}\""),
            table::Setting::Bool { .. } => "true".to_string(),
            table::Setting::Int => "1".to_string(),
            // The first keyword the snapshot lists — a value chosen by the
            // table rather than by whoever wrote this test.
            table::Setting::Enum => format!(
                "\"{}\"",
                entry
                    .params
                    .first()
                    .and_then(|param| param.members().first())
                    .unwrap_or_else(|| panic!("`{field}` is an enum with no members"))
            ),
            table::Setting::Handled(_) => unreachable!("filtered above"),
        };
        source.push_str(&format!("\t{field} = {value},\n"));
    }

    source.push_str(
        "}\n\ninstaller {\n\tsection(\"Core\", function()\n\
         \t\tdetailPrint(\"installing\")\n\tend),\n}\n",
    );
    source
}

#[test]
fn every_attribute_row_emits() {
    let mut diags = Diagnostics::new();
    let built = installua::build(&attribute_program(), &mut diags);

    assert!(
        built.is_some() && !diags.has_errors(),
        "{}",
        diags.render("overlay-attributes.lua")
    );
}

#[test]
fn the_attributes_match_their_golden() {
    let mut diags = Diagnostics::new();
    let built = installua::build(&attribute_program(), &mut diags).unwrap_or_default();

    let expected = include_str!("golden/overlay-attributes.nsi");
    assert_eq!(
        built, expected,
        "regenerate with:\n  cargo test --test overlay -- --ignored write_the_golden"
    );
}

#[test]
fn every_exposed_row_carries_an_example() {
    // §14: this is what makes "added an instruction, forgot the test"
    // unrepresentable rather than merely discouraged.
    let missing: Vec<&str> = table::overlay::ROWS
        .iter()
        .filter(|row| row.class == Class::Exposed && row.example.is_none())
        .map(|row| row.nsis)
        .collect();

    assert_eq!(missing, Vec::<&str>::new());
}

#[test]
fn every_example_compiles() {
    // Separately from the golden, because a golden that has not been
    // regenerated and a program that no longer compiles fail the same test
    // otherwise, and they are different problems.
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags);

    assert!(
        built.is_some() && !diags.has_errors(),
        "{}",
        diags.render("overlay-examples.lua")
    );
}

#[test]
fn the_examples_match_their_golden() {
    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags).unwrap_or_default();

    let expected = include_str!("golden/overlay-examples.nsi");
    assert_eq!(
        built, expected,
        "regenerate with:\n  cargo test --test overlay -- --ignored write_the_golden"
    );
}

/// The two things an example cannot show, because an example is one call site
/// and these differ *between* call sites.
#[test]
fn an_optional_position_is_written_only_when_something_after_it_is() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             local f = fileOpen(INSTDIR .. \"/log.txt\", \"r\")\n\
             {body}\n\
             f:close()\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    // The output is optional, so a call nobody reads writes no register. A
    // temporary here would be correct NSIS and would still enter the clobber
    // set, costing a caller a save for a value that was never wanted.
    let discarded = build("f:seek(0, \"END\")");
    assert!(
        discarded.contains("FileSeek $0 0 \"END\"\n"),
        "an unread optional output should not be emitted:\n{discarded}"
    );

    // And `mode` is optional but *precedes* the output, so reading the result
    // means writing a mode the author never named — `FileSeek $0 0 $1` is not
    // an option, NSIS reads `$1` as the mode and rejects the line.
    let filled = build("local p = f:seek(0)\ndetailPrint(\"at \" .. p)");
    assert!(
        filled.contains("FileSeek $0 0 SET $1\n"),
        "reaching the output should fill `mode`:\n{filled}"
    );

    // Same position, same row, nothing after it: not written.
    let bare = build("f:seek(0)");
    assert!(
        bare.contains("FileSeek $0 0\n"),
        "a trailing optional stays absent:\n{bare}"
    );
}

/// Optional positions are named, and naming one writes every position before it.
///
/// This is the rule an example cannot show either, because an example is one
/// call site and the point is which *other* call sites are now writable.
/// `createShortcut` is the case that motivated it: setting the description used
/// to mean writing all nine arguments, four of which the author does not care
/// about and three of which are enums they would have to look up.
#[test]
fn an_optional_position_is_reached_by_name_and_fills_the_ones_before_it() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             {body}\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    // The last option, and the five before it are the compiler's problem.
    // `iconIndex`'s `0` is one argument rather than two: `-CMDHELP` prints
    // `icon index`, and that is one NSIS argument whose name has a space in it.
    let comment = build(
        "createShortcut(DESKTOP .. \"/App.lnk\", INSTDIR .. \"/app.exe\", \
         { comment = \"Launch App\" })",
    );
    assert!(
        comment.contains(
            "CreateShortcut \"$DESKTOP\\App.lnk\" \"$INSTDIR\\app.exe\" \"\" \"\" 0 \
             SW_SHOWNORMAL \"\" \"Launch App\"\n"
        ),
        "reaching `comment` should fill the five positions before it:\n{comment}"
    );

    // Nothing named: nothing filled. The two required positions are the line.
    let bare = build("createShortcut(DESKTOP .. \"/App.lnk\", INSTDIR .. \"/app.exe\")");
    assert!(
        bare.contains("CreateShortcut \"$DESKTOP\\App.lnk\" \"$INSTDIR\\app.exe\"\n"),
        "an unnamed option stays absent:\n{bare}"
    );

    // A leading optional, which is what counting could never do: `"open"` is
    // the first *required* position, so it can only mean `verb`.
    let shell = build("execShell(\"open\", \"https://example.invalid\", { invokeIdList = true })");
    assert!(
        shell.contains("ExecShell /INVOKEIDLIST \"open\" \"https://example.invalid\"\n"),
        "a toggle is spelled by the compiler and placed by the table:\n{shell}"
    );

    // And `false` is the absence rather than a token, so it emits nothing.
    let off = build("execShell(\"open\", \"https://example.invalid\", { invokeIdList = false })");
    assert!(
        off.contains("ExecShell \"open\" \"https://example.invalid\"\n"),
        "`false` is not a flag:\n{off}"
    );
}

/// The other half of the options table: the flags, which were never positions.
#[test]
fn a_flag_is_reached_by_name_and_placed_by_the_table() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             {body}\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    // `/r` is what NSIS calls it and `recursive` is what it does. Both flags in
    // one table, in the snapshot's order rather than the caller's.
    let both = build("rmDir(INSTDIR, { rebootOk = true, recursive = true })");
    assert!(
        both.contains("RMDir /r /REBOOTOK $INSTDIR\n"),
        "flags are emitted in table order, not the order they were written:\n{both}"
    );

    // `false` is the absence rather than a token, exactly as it is for a toggle.
    let off = build("rmDir(INSTDIR, { recursive = false })");
    assert!(
        off.contains("RMDir $INSTDIR\n"),
        "`false` is not a flag:\n{off}"
    );

    // `Opt::after` is a place in the emitted line and not an argument index:
    // `/SHORT` goes in front of the *output* register, which no counting of the
    // caller's arguments could have worked out.
    let short = build("local full = getFullPathName(INSTDIR, { short = true })\ndetailPrint(full)");
    assert!(
        short.contains("GetFullPathName /SHORT $0 $INSTDIR\n"),
        "a flag can precede an output:\n{short}"
    );

    // Both halves of the table on one row: `sizeInKb` is an unambiguous
    // trailing optional and stays an argument, and the flags never were one.
    let copy =
        build("copyFiles(INSTDIR .. \"/data\", INSTDIR .. \"/backup\", 100, { silent = true })");
    assert!(
        copy.contains("CopyFiles /SILENT \"$INSTDIR\\data\" \"$INSTDIR\\backup\" 100\n"),
        "a counted optional and a named flag coexist:\n{copy}"
    );

    // And the flag nobody writes. `WriteRegMultiStr` without `/REGEDIT5` is an
    // error rather than a different instruction, so the compiler supplies it.
    let multi = build("writeRegMultiStr(HKLM, \"Software/Example\", \"List\", \"660000000000\")");
    assert!(
        multi.contains("WriteRegMultiStr /REGEDIT5 HKLM \"Software\\Example\" \"List\""),
        "a required flag is written without being named:\n{multi}"
    );
}

/// A flag that carries a value, in the two shapes the table has for it.
///
/// `File`'s `/x` is a list because it repeats, and `MessageBox`'s `/SD` is a
/// field of §15.18's own table because its value has to be an answer the
/// buttons beside it can give. Neither is a position, and neither is a `bool`.
#[test]
fn a_flag_can_carry_a_value() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             {body}\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    // One `/x` per element, in the order they were written, each a path: §5's
    // `/` → `\` applies to an exclusion as much as to the filespec it excludes.
    let excluded = build(
        "file(\"assets/icon.ico\", { recursive = true, exclude = { \"build/*.tmp\", \"*.log\" } })",
    );
    assert!(
        excluded.contains("File /r /x \"build\\*.tmp\" /x \"*.log\" \"assets\\icon.ico\"\n"),
        "a list is one flag per element:\n{excluded}"
    );

    // An empty list is no flag at all, the way `false` is.
    let none = build("file(\"assets/icon.ico\", { exclude = {} })");
    assert!(
        none.contains("File \"assets\\icon.ico\"\n"),
        "an empty list writes nothing:\n{none}"
    );

    // `/SD` follows the text, which is where `Opt::after` says it goes, and the
    // answer is spelled the way `messageBox` returns it rather than as `IDNO`.
    let silent =
        build("messageBox { text = \"Restart?\", buttons = \"YESNO\", silentAnswer = \"NO\" }");
    assert!(
        silent.contains("MessageBox MB_YESNO \"Restart?\" /SD IDNO\n"),
        "the silent answer is written where NSIS wants it:\n{silent}"
    );
}

/// The two errors a valued flag can give that a `bool` one cannot.
#[test]
fn a_valued_flag_says_what_it_wants() {
    let errors = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             {body}\n\
             end), }}"
        );
        let built = installua::build(&source, &mut diags);
        assert!(built.is_none() || diags.has_errors(), "{body} was accepted");
        diags.render("<test>")
    };

    // Not a `bool`, so "on or off" would be the wrong sentence.
    let scalar = errors("file(\"assets/icon.ico\", { exclude = \"*.tmp\" })");
    assert!(
        scalar.contains("`exclude` is a list") && scalar.contains("`/x` for each"),
        "{scalar}"
    );

    // An answer this dialog cannot give. NSIS accepts `/SD IDYES` under
    // `MB_OKCANCEL` and the silent install then takes a branch nobody wrote,
    // which is exactly why the check is here and not there.
    let impossible =
        errors("messageBox { text = \"Go?\", buttons = \"OKCANCEL\", silentAnswer = \"YES\" }");
    assert!(
        impossible.contains("`OKCANCEL` cannot answer `YES`")
            && impossible.contains("`OK`, `CANCEL`"),
        "{impossible}"
    );
}

/// The error that replaces "takes 2 to 9 arguments, and 4 were given".
#[test]
fn an_unknown_option_names_the_ones_that_exist() {
    let mut diags = Diagnostics::new();
    let built = installua::build(
        "attributes { outFile = \"a.exe\" }\n\
         installer { section(\"Core\", function()\n\
         execShell(\"open\", \"https://example.invalid\", { showmode = \"SW_HIDE\" })\n\
         end), }",
        &mut diags,
    );

    assert!(built.is_none() || diags.has_errors());
    let rendered = diags.render("<test>");
    assert!(
        rendered.contains("`execShell` has no option `showmode`")
            && rendered.contains("`invokeIdList`, `parameters`, `showMode`"),
        "{rendered}"
    );

    // A flag is in the same list, because a caller has no reason to know which
    // half of the table a name comes from.
    let mut diags = Diagnostics::new();
    let built = installua::build(
        "attributes { outFile = \"a.exe\" }\n\
         installer { section(\"Core\", function()\n\
         rmDir(INSTDIR, { REBOOTOK = true })\n\
         end), }",
        &mut diags,
    );

    assert!(built.is_none() || diags.has_errors());
    let rendered = diags.render("<test>");
    assert!(
        rendered.contains("`rmDir` has no option `REBOOTOK`")
            && rendered.contains("`recursive`, `rebootOk`"),
        "{rendered}"
    );
}

/// A row that writes two registers, called by someone who wants one or none.
///
/// The example on the row binds both, because that is the shape worth showing.
/// What it cannot show is that `GetFileTime` has no one-register spelling: the
/// second output is written whatever Lua asked for, so the only question is
/// whether it lands in a name or a temporary.
#[test]
fn every_required_output_is_written_even_when_nothing_binds_it() {
    let build = |body: &str| {
        let mut diags = Diagnostics::new();
        let source = format!(
            "attributes {{ outFile = \"a.exe\" }}\n\
             installer {{ section(\"Core\", function()\n\
             {body}\n\
             end), }}"
        );
        installua::build(&source, &mut diags)
            .unwrap_or_else(|| panic!("{}", diags.render("<test>")))
    };

    let both = build(
        "local high, low = getFileTime(INSTDIR .. \"/app.exe\")\n\
         detailPrint(high .. \" \" .. low)",
    );
    assert!(
        both.contains("GetFileTime \"$INSTDIR\\app.exe\" $0 $1\n"),
        "two names, two registers:\n{both}"
    );

    // One name. Lua adjusts the call to one value and NSIS does not adjust
    // anything, so the dropped half still needs somewhere to land.
    let one = build(
        "local high = getFileTime(INSTDIR .. \"/app.exe\")\n\
         detailPrint(\"stamp \" .. high)",
    );
    assert!(
        one.contains("GetFileTime \"$INSTDIR\\app.exe\" $0 $1\n"),
        "an unbound required output should still take a register:\n{one}"
    );

    // No names at all: the call is a statement, and both halves are temporary.
    let none = build("getFileTime(INSTDIR .. \"/app.exe\")");
    assert!(
        none.contains("GetFileTime \"$INSTDIR\\app.exe\" $0 $1\n"),
        "statement position writes the same two registers:\n{none}"
    );
}

/// Binding more names than the row has outputs. There is no `nil` to pad with
/// (§3), so this is an arity error rather than a shorter tuple.
#[test]
fn binding_more_names_than_a_row_writes_is_an_error() {
    let mut diags = Diagnostics::new();
    let built = installua::build(
        "attributes { outFile = \"a.exe\" }\n\
         installer { section(\"Core\", function()\n\
         local high, low, extra = getFileTime(INSTDIR .. \"/app.exe\")\n\
         end), }",
        &mut diags,
    );

    assert!(built.is_none() || diags.has_errors());
    let rendered = diags.render("<test>");
    assert!(
        rendered.contains("writes 2 register(s), and 3 are being bound"),
        "{rendered}"
    );
}

/// Tier 3, with an empty warning allowlist (§14).
///
/// The golden above answers *"did the output change?"*. Only `makensis`
/// answers *"is the output valid NSIS?"*, and the two are not the same
/// question: swap `CreateShortcut`'s link and target and the golden passes
/// forever, because it records what the compiler emits rather than what NSIS
/// accepts. Phase 6 writes a row per command from a `-CMDHELP` line somebody
/// read, so that is the failure this is here for.
///
/// Skips cleanly when there is no `makensis`, the same trade §14 makes
/// everywhere else.
#[test]
fn the_examples_assemble_under_wx() {
    let Some(makensis) = makensis() else {
        eprintln!("skipping: `makensis` is not installed");
        return;
    };

    let mut diags = Diagnostics::new();
    let built = installua::build(&program(), &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay-examples.lua")));

    // `File` resolves relative to the script, so the script goes where the
    // fixtures are — see tests/fixtures/README.md.
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures");
    let script = fixtures.join("assembling.nsi");
    std::fs::write(&script, &built).expect("write the script");

    let output = Command::new(&makensis)
        .arg("-WX")
        .arg(&script)
        .current_dir(&fixtures)
        .output()
        .expect("run makensis");

    let _ = std::fs::remove_file(&script);
    let _ = std::fs::remove_file(fixtures.join("examples.exe"));

    assert!(
        output.status.success(),
        // Both streams: `makensis` prints its progress to stdout and the line
        // that says why to stderr, and only one of those is the message.
        "makensis -WX rejected the overlay examples:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

/// The same question for the attributes: a `Setting` is a claim about what NSIS
/// accepts in that position, and only `makensis` can refuse it.
#[test]
fn the_attributes_assemble_under_wx() {
    let Some(makensis) = makensis() else {
        eprintln!("skipping: `makensis` is not installed");
        return;
    };

    let mut diags = Diagnostics::new();
    let built = installua::build(&attribute_program(), &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay-attributes.lua")));

    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures");
    let script = fixtures.join("attributes.nsi");
    std::fs::write(&script, &built).expect("write the script");

    let output = Command::new(&makensis)
        .arg("-WX")
        .arg(&script)
        .current_dir(&fixtures)
        .output()
        .expect("run makensis");

    let _ = std::fs::remove_file(&script);
    let _ = std::fs::remove_file(fixtures.join("outFile.out"));

    assert!(
        output.status.success(),
        "makensis -WX rejected the attribute rows:\n{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn makensis() -> Option<String> {
    let name = std::env::var("MAKENSIS").unwrap_or_else(|_| "makensis".to_string());
    Command::new(&name)
        .arg("-VERSION")
        .output()
        .ok()
        .filter(|output| output.status.success())
        .map(|_| name)
}

/// Regenerates the golden and the source beside it. Ignored, because a test
/// that rewrites its own expectation is not a test.
#[test]
#[ignore = "regenerates tests/golden/overlay-examples.{lua,nsi}"]
fn write_the_golden() {
    let source = program();
    let mut diags = Diagnostics::new();
    let built = installua::build(&source, &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay.lua")));

    std::fs::write("tests/golden/overlay-examples.lua", source).unwrap();
    std::fs::write("tests/golden/overlay-examples.nsi", built).unwrap();

    let source = attribute_program();
    let mut diags = Diagnostics::new();
    let built = installua::build(&source, &mut diags)
        .unwrap_or_else(|| panic!("{}", diags.render("overlay-attributes.lua")));

    std::fs::write("tests/golden/overlay-attributes.lua", source).unwrap();
    std::fs::write("tests/golden/overlay-attributes.nsi", built).unwrap();
}
