---@meta

-- Generated by `installua stubs`. Do not edit.
--
-- `---@meta` marks this file as definitions-only: it contributes no runtime
-- code and its own contents are not diagnosed. Everything here comes from the
-- same table the compiler checks against (§15.23), so the editor and the
-- compiler cannot disagree about what exists.

--------------------------------------------------------------------------------
-- Enums, as `---@alias`. An alias of string literals completes *inside* the
-- quotes, which a plain `string` does not.
--------------------------------------------------------------------------------

---@alias installua.Toporleftorbottomorright
---| '"top"'
---| '"left"'
---| '"bottom"'
---| '"right"'

---@alias installua.Heightorwidth
---| '"height"'
---| '"width"'

---@alias installua.ShowMode
---| '"SW_SHOWNORMAL"'
---| '"SW_SHOWMAXIMIZED"'
---| '"SW_SHOWMINIMIZED"'

---@alias installua.HotKey
---| '"ALT"'
---| '"CONTROL"'
---| '"EXT"'
---| '"SHIFT"'
---| '"F1-F24"'
---| '"A-Z"'

---@alias installua.RootKey
---| '"HKCR"'
---| '"HKCR32"'
---| '"HKCR64"'
---| '"HKLM"'
---| '"HKLM32"'
---| '"HKLM64"'
---| '"HKCU"'
---| '"HKCU32"'
---| '"HKCU64"'
---| '"HKU"'
---| '"HKCC"'
---| '"HKDD"'
---| '"HKPD"'
---| '"SHCTX"'

---@alias installua.Verb
---| '"open"'
---| '"print"'

---@alias installua.OpenMode
---| '"r"'
---| '"w"'
---| '"a"'

---@alias installua.Mode
---| '"SET"'
---| '"CUR"'
---| '"END"'

---@alias installua.Field
---| '"MAJOR"'
---| '"MINOR"'
---| '"BUILD"'
---| '"SERVICEPACK"'

---@alias installua.Falseortrue
---| '"false"'
---| '"true"'

---@alias installua.Compress
---| '"off"'
---| '"auto"'
---| '"force"'

---@alias installua.Compressor
---| '"zlib"'
---| '"bzip2"'
---| '"lzma"'

---@alias installua.Hideorshow
---| '"hide"'
---| '"show"'

---@alias installua.Noneorlistonlyortextonlyorbothorlastused
---| '"none"'
---| '"listonly"'
---| '"textonly"'
---| '"both"'
---| '"lastused"'

---@alias installua.Attribute
---| '"NORMAL"'
---| '"ARCHIVE"'
---| '"HIDDEN"'
---| '"OFFLINE"'
---| '"READONLY"'
---| '"SYSTEM"'
---| '"TEMPORARY"'
---| '"0"'

---@alias installua.Overwrite
---| '"on"'
---| '"off"'
---| '"try"'
---| '"ifnewer"'
---| '"ifdiff"'

---@alias installua.Trueorfalse
---| '"true"'
---| '"false"'

---@alias installua.32or64ordefaultorlastused
---| '"32"'
---| '"64"'
---| '"default"'
---| '"lastused"'

---@alias installua.Allorcurrentorlastused
---| '"all"'
---| '"current"'
---| '"lastused"'

---@alias installua.Silentornormal
---| '"silent"'
---| '"normal"'

---@alias installua.Showinstdetails
---| '"hide"'
---| '"show"'
---| '"nevershow"'

---@alias installua.Showuninstdetails
---| '"hide"'
---| '"show"'
---| '"nevershow"'

---@alias installua.Silentinstall
---| '"normal"'
---| '"silent"'
---| '"silentlog"'

---@alias installua.Silentuninstall
---| '"normal"'
---| '"silent"'

---@alias installua.Cpu
---| '"x86"'
---| '"amd64"'

---@alias installua.ExecutionLevel
---| '"none"'
---| '"user"'
---| '"highest"'
---| '"admin"'

---@alias installua.SupportedOS
---| '"none"'
---| '"all"'
---| '"WinVista"'
---| '"Win7"'
---| '"Win8"'
---| '"Win8.1"'
---| '"Win10"'
---| string

---@alias installua.Onoroff
---| '"on"'
---| '"off"'

--------------------------------------------------------------------------------
-- Blocks (§15.10). Field names come from the overlay's `Attribute` rows.
--------------------------------------------------------------------------------

---@class (exact) installua.VersionInfo
---@field product? string
---@field file? string
---@field keys? table<string, string|table<string, string>>

---@class (exact) installua.Installer
---@field checkBitmap? string
---@field installColors? string
---@field progressBar? string[]
---@field licenseBkColor? string

---@class (exact) installua.PortableExecutable
---@field addResource? { file: string, restype: string, resname: string, reslang?: string }[]
---@field removeResource? { restype: string, resname: string, reslang: string }[]
---@field dllCharacteristics? { add: integer, remove: integer }
---@field subsystemVersion? string

---@class (exact) installua.Manifest
---@field customStrings? { path: string, string: string }[]
---@field dpiAware? boolean
---@field dpiAwareness? string
---@field longPathAware? boolean
---@field supportedOS? installua.SupportedOS[]
---@field maxVersionTested? string
---@field disableWindowFiltering? boolean
---@field gdiScaling? boolean

---@class (exact) installua.Attributes
---@field brandingImage? { edge: installua.Toporleftorbottomorright, size: string, padding?: string }
---@field autoCloseWindow? boolean
---@field bgFont? { face?: string, height?: integer, weight?: integer }
---@field bgGradient? false|{ top: string, bottom?: string, text?: string }
---@field brandingText? string
---@field caption? string
---@field crcCheck? boolean
---@field datablockOptimize? boolean
---@field allowRootDirInstall? boolean
---@field fileBufSize? integer
---@field fileErrorText? { text?: string, withoutIgnore?: string }
---@field icon? string
---@field installDirRegKey? { root: installua.RootKey, key: string, name: string }
---@field installDir? string
---@field name? string
---@field outFile string
---@field compress? installua.Compress
---@field compressor? installua.Compressor
---@field compressorDictSize? integer
---@field compressionLevel? integer
---@field dateSave? boolean
---@field font? { face: string, size: integer }
---@field overwrite? installua.Overwrite
---@field showInstDetails? installua.Showinstdetails
---@field showUninstDetails? installua.Showuninstdetails
---@field silentInstall? installua.Silentinstall
---@field silentUninstall? installua.Silentuninstall
---@field cpu? installua.Cpu
---@field unicode? boolean
---@field uninstallCaption? string
---@field windowIcon? boolean
---@field requestExecutionLevel? installua.ExecutionLevel
---@field buttonText? { back?: string, next?: string, cancel?: string, close?: string }
---@field detailsButtonText? string
---@field uninstallButtonText? string
---@field installButtonText? string
---@field spaceTexts? false|{ required: string, available?: string }
---@field completedText? string
---@field allowSkipFiles? boolean
---@field installer? installua.Installer
---@field portableExecutable? installua.PortableExecutable
---@field manifest? installua.Manifest
---@field versionInfo? installua.VersionInfo

---@class (exact) installua.Installer
---@field installDir? string
---@field icon? string
---@field caption? string
---@field installTypes? string[]
---@field checkBitmap? string
---@field installColors? string
---@field progressBar? string
---@field licenseBkColor? string
---@field headerColors? installua.Colors
---@field abortPrompt? boolean|{ text?: string, default?: string }
---@field autoClose? boolean
---@field headerImage? string|boolean|{ file?: string, stretch?: string, rtl?: string|{ file: string, stretch?: string }, right?: boolean, transparentText?: boolean }
---@field wizardImage? string|{ file: string, stretch?: string }
---@field smallDescriptions? boolean

---@param options installua.Attributes
function attributes(options) end

---@param options installua.Installer
function installer(options) end

---@param options installua.Installer
function uninstaller(options) end

---@class (exact) installua.Ask
---@field title? string
---@field info? string
---@field allLanguages? boolean
---@field alwaysShow? boolean
---@field remember? { root: string, key: string, value: string }

---@class (exact) installua.Languages
---@field locales table<string, table<string, string>>
---@field ask? installua.Ask

---@param options installua.Languages
function languages(options) end

--- The strings `languages {}` declared. A read is `$(name)`, resolved
--- against `$LANGUAGE` at run time (§15.26).
---@type table<string, string>
lang = {}

-- The hooks every page has, and the header strip five of the eight draw into.
-- `welcome` and `finish` are full-window pages with no header, which is why
-- they inherit the bare class and the other six inherit the headed one.
---@class (exact) installua.Page
---@field pre? fun()
---@field show? fun()
---@field leave? fun()

---@class (exact) installua.Page.Headed : installua.Page
---@field headerText? string
---@field headerSubText? string

---@class (exact) installua.Page.Welcome : installua.Page
---@field title? string|{ text: string, lines: integer }
---@field text? string
---@field destroyed? fun()

---@class (exact) installua.Page.License : installua.Page.Headed
---@field file string
---@field subCaption? string
---@field topText? string
---@field bottomText? string
---@field button? string
---@field checkbox? string
---@field radioButtons? { accept?: string, decline?: string }

---@class (exact) installua.Page.Components : installua.Page.Headed
---@field subCaption? string
---@field topText? string
---@field instTypeText? string
---@field listText? string
---@field descriptionTitle? string
---@field descriptionText? string

---@class (exact) installua.Page.Directory : installua.Page.Headed
---@field subCaption? string
---@field topText? string
---@field destinationText? string
---@field variable? string
---@field verifyOnLeave? boolean
---@field colors? installua.Colors

-- `registry` is one field holding three because MUI2 reads the three only
-- together: any one of them alone is a define nothing looks at.
---@class (exact) installua.Page.StartMenu : installua.Page.Headed
---@field defaultFolder? string
---@field topText? string
---@field checkbox? boolean|string
---@field registry? { root: string, key: string, value: string }
---@field destroyed? fun()

---@class (exact) installua.Page.InstFiles : installua.Page.Headed
---@field subCaption? string
---@field finishHeaderText? string
---@field finishHeaderSubText? string
---@field abortHeaderText? string
---@field abortHeaderSubText? string

-- `run` and `readme` are each a program to start or a function to call, and
-- they are two shapes rather than one with optional members: MUI2 expands the
-- parameters only where there is no function to call.
---@class (exact) installua.Page.Finish : installua.Page
---@field title? string|{ text: string, lines: integer }
---@field text? string|{ text: string, large: boolean }
---@field button? string
---@field cancelEnabled? boolean
---@field reboot? boolean|{ text?: string, now?: string, later?: string, default?: string }
---@field run? { path: string, parameters?: string, text?: string, checked?: boolean }|{ call: fun(), text?: string, checked?: boolean }
---@field readme? { path: string, text?: string, checked?: boolean }|{ call: fun(), text?: string, checked?: boolean }
---@field link? { text: string, url: string, color?: string }
---@field destroyed? fun()

---@class (exact) installua.Page.Confirm : installua.Page.Headed
---@field subCaption? string
---@field topText? string
---@field locationText? string
---@field variable? string

---@class (exact) installua.Page.Custom : installua.Page.Headed
---@field [1]? string
---@field controls? table

-- The one page bound to a local — `local menu = page.startMenu { … }` — because
-- MUI2 names it from install-time code: the folder is read back through the id
-- and the shortcut writing is wrapped in it (§13).
---@class (exact) installua.StartMenu
---@field folder string The folder the page chose. Read-only.
local StartMenu = {}

--- Wraps the code that creates the shortcuts, so the chosen folder is written
--- back to the registry. The installer's; the uninstaller reads `folder`.
---@param body fun()
function StartMenu.write(body) end

---@class installua.Pages
---@field welcome fun(options?: installua.Page.Welcome)
---@field license fun(options: installua.Page.License)
---@field components fun(options?: installua.Page.Components)
---@field directory fun(options?: installua.Page.Directory)
---@field startMenu fun(options?: installua.Page.StartMenu): installua.StartMenu
---@field instFiles fun(options?: installua.Page.InstFiles)
---@field finish fun(options?: installua.Page.Finish)
---@field confirm fun(options?: installua.Page.Confirm)
---@field custom fun(options?: installua.Page.Custom)

---@type installua.Pages
page = {}

--------------------------------------------------------------------------------
-- Declarations (§15.10). These are language constructs rather than
-- instructions, so they are written here rather than generated.
--------------------------------------------------------------------------------

-- §15.23's pair: a short form when there is nothing to configure, and a
-- table form when there is. The table's array part is the parameters and
-- its hash part the options, as `file { "docs/", recursive = true }` is
-- `File /r "docs\"`.

---@class (exact) installua.SectionOptions
---@field [1] string The section's name, written first and without a key.
---@field body fun() What the section installs.
---@field optional? boolean Starts unticked in the components tree.
---@field required? boolean Always installed, with no box to untick.
---@field installTypes? string[] Which of the block's `installTypes` this belongs to.
---@field size? integer Extra kilobytes to charge, beyond the files installed.
---@field description? string The words the components page shows on hover.
local SectionOptions = {}

---@param name string
---@param body fun()
---@return installua.Section
---@overload fun(options: installua.SectionOptions): installua.Section
function section(name, body) end

---@class (exact) installua.GroupOptions
---@field [1] string The group's heading, written first and without a key.
---@field sections table The sections it holds.
---@field expanded? boolean Opens the heading in the components tree.
---@field description? string The words the components page shows on hover.
local GroupOptions = {}

---@param name string
---@param sections table
---@return installua.Group
---@overload fun(options: installua.GroupOptions): installua.Group
function group(name, sections) end

-- What a bound `section` is at install time: the handle §13's binding
-- produces. Every field is readable and writable, and the section index
-- NSIS reads is the compiler's — it appears in no Installua source.
---@class (exact) installua.Selectable
---@field selected boolean Ticked in the components tree (`SF_SELECTED`).
---@field readOnly boolean Installed with no box to untick (`SF_RO`).
---@field bold boolean Drawn bold in the components tree (`SF_BOLD`).
---@field text string The row the tree draws; `""` draws none.
local Selectable = {}

---@class (exact) installua.Section : installua.Selectable
---@field size integer Kilobytes charged beyond the files installed.
---@field installTypes string[] Which of the block's `installTypes` it belongs to.
local Section = {}

-- A group is a section to NSIS — one index, one flags word — plus the
-- one bit only a heading has, and minus the two only a section has: a
-- group is charged no space and belongs to no install type, because
-- what it holds is sections and each of those answers for itself.
---@class (exact) installua.Group : installua.Selectable
---@field expanded boolean Opens the heading in the components tree (`SF_EXPAND`).
local Group = {}

-- The install type the user picked, by the name the block declared, and
-- `""` for the custom one every list has and no list declares (§13).
---@type string
currentInstType = nil

-- The block's install types, addressed by name because an install type
-- is a line in a block's field and there is nothing to bind (§13).
---@class installua.InstTypes
instTypes = {}

---@param name string
---@param body function
function func(name, body) end

---@param body fun()
function onInit(body) end

-- Source layout, not a module system: the file's declarations are
-- merged into this one and nothing is emitted (§15.28). The names it
-- contributes come from `project.lua` beside this file, since
-- `lua-language-server` cannot follow the merge itself.
---@param path string
function include(path) end

-- The two iterators, and the halves they run in. `glob` is expanded on
-- the build machine and its loop is unrolled, so the pattern has to be
-- known there (§7); `lines` runs at install time, over a handle
-- `fileOpen` returned.
---@param pattern string
---@return fun(): string
function glob(pattern) end

---@param handle installua.File
---@return fun(): string
function lines(handle) end

---@param header string
---@return table
function import(header) end

---@param name string
---@return table
function plugin(name) end

---@param text string
function raw(text) end

---@param options string|table
---@return string
function messageBox(options) end

---@param path string
---@param mode installua.OpenMode
---@return installua.File
function fileOpen(path, mode) end

---@class installua.File
local File = {}

function File:close() end

---@param maxlen? integer
---@return string
function File:read(maxlen) end

---@param text string
function File:write(text) end

---@return integer
function File:readByte() end

---@param bytevalue integer
function File:writeByte(bytevalue) end

---@param maxlen? integer
---@return string
function File:readUtf16Le(maxlen) end

---@param text string
---@param options? { bom: boolean }
function File:writeUtf16Le(text, options) end

---@return integer
function File:readWord() end

---@param wordvalue integer
function File:writeWord(wordvalue) end

---@param offset integer
---@param mode? installua.Mode
---@return integer
function File:seek(offset, mode) end

-- The controls a `page.custom` draws (§15.32), in §15.23's table form: the
-- array part is the text the control is drawn with and the hash part is
-- where it sits. A control is listed by a page's `controls`, and the
-- `local` it is bound to decides nothing about its position.

---@class (exact) installua.ControlOptions
---@field [1]? string The text it is drawn with, where it has one.
---@field x? integer|string From the left edge; defaults to 0.
---@field y? integer|string From the top. Required: there is no auto-flow.
---@field width? integer|string Defaults to the width of the dialog.
---@field height? integer|string Required, for the same reason as `y`.
---@field items? string[] The rows of a `dropList` or a `listBox`.
---@field image? string The `.bmp` a `bitmap` draws.
---@field onClick? fun() Called when it is clicked.
---@field onChange? fun() Called when what it holds changes.
---@field url? string An `onClick` that opens an address.
local ControlOptions = {}

-- A colour is six hexadecimal digits, in the order Windows writes them.
-- Both are named because `SetCtlColors` writes both in one instruction.
---@class (exact) installua.Colors
---@field text string
---@field background string Or `"transparent"`, to leave it unpainted.
local Colors = {}

---@class (exact) installua.Font
---@field face string A typeface name; Windows substitutes if it has none.
---@field size integer In points, as a word processor would say it.
---@field bold? boolean
local Font = {}

-- What a bound control is at install time. The window handle NSIS reads
-- is the compiler's: it appears in no Installua source.
--
-- Five of the seven fields are write-only, because Windows offers no
-- instruction that reports them: NSIS can set a control's colours and
-- cannot ask what they are.
---@class (exact) installua.Control
---@field value string Its text.
---@field checked boolean A `checkbox`'s or a `radioButton`'s tick.
---@field enabled boolean Write-only.
---@field visible boolean Write-only.
---@field colors installua.Colors Write-only.
---@field font installua.Font Write-only.
---@field image string Write-only; a `bitmap`'s picture.
local Control = {}

---@param options installua.ControlOptions
---@return installua.Control
function label(options) end

---@param options installua.ControlOptions
---@return installua.Control
function text(options) end

---@param options installua.ControlOptions
---@return installua.Control
function password(options) end

---@param options installua.ControlOptions
---@return installua.Control
function number(options) end

---@param options installua.ControlOptions
---@return installua.Control
function button(options) end

---@param options installua.ControlOptions
---@return installua.Control
function checkbox(options) end

---@param options installua.ControlOptions
---@return installua.Control
function radioButton(options) end

---@param options installua.ControlOptions
---@return installua.Control
function groupBox(options) end

---@param options installua.ControlOptions
---@return installua.Control
function hLine(options) end

---@param options installua.ControlOptions
---@return installua.Control
function dropList(options) end

---@param options installua.ControlOptions
---@return installua.Control
function listBox(options) end

---@param options installua.ControlOptions
---@return installua.Control
function fileRequest(options) end

---@param options installua.ControlOptions
---@return installua.Control
function dirRequest(options) end

---@param options installua.ControlOptions
---@return installua.Control
function bitmap(options) end

---@param options installua.ControlOptions
---@return installua.Control
function link(options) end

--------------------------------------------------------------------------------
-- Instructions, one per `Class::Exposed` row (§15.23).
--------------------------------------------------------------------------------

---@param message? string
function abort(message) end

function bringToFront() end

function clearErrors() end

---@param filename string
---@param options? { productVersion: boolean }
---@return integer
---@return integer
function getDllVersion(filename, options) end

---@param localfilename string
---@return integer
---@return integer
function getDllVersionLocal(localfilename) end

---@param file string
---@return integer
---@return integer
function getFileTime(file) end

---@param localfile string
---@return integer
---@return integer
function getFileTimeLocal(localfile) end

---@param source_path string
---@param destination_path string
---@param total_size_in_kb? integer
---@param options? { silent: boolean, filesOnly: boolean }
function copyFiles(source_path, destination_path, total_size_in_kb, options) end

---@param directory_name string
function createDirectory(directory_name) end

---@param shortcut_name_lnk string
---@param shortcut_target string
---@param options? { parameters: string, iconFile: string, iconIndex: integer, showMode: installua.ShowMode, hotkey: installua.HotKey, comment: string, noWorkingDir: boolean }
function createShortcut(shortcut_name_lnk, shortcut_target, options) end

---@param ini_file string
---@param section_name string
function deleteIniSection(ini_file, section_name) end

---@param ini_file string
---@param section_name string
---@param entry_name string
function deleteIniStr(ini_file, section_name, entry_name) end

---@param root_key installua.RootKey
---@param subkey string
---@param options? { ifEmpty: boolean }
function deleteRegKey(root_key, subkey, options) end

---@param root_key installua.RootKey
---@param subkey string
---@param entry_name string
function deleteRegValue(root_key, subkey, entry_name) end

---@param filespec string
---@param options? { rebootOk: boolean }
function delete(filespec, options) end

---@param message string
function detailPrint(message) end

---@return integer
function getInstDirError() end

---@param rootkey installua.RootKey
---@param subkey string
---@param index integer
---@return string
function enumRegKey(rootkey, subkey, index) end

---@param rootkey installua.RootKey
---@param subkey string
---@param index integer
---@return string
function enumRegValue(rootkey, subkey, index) end

---@param command_line string
function exec(command_line) end

---@param command_line string
---@return integer
function execWait(command_line) end

---@param verb installua.Verb
---@param file string
---@param options? { invokeIdList: boolean, parameters: string, showMode: installua.ShowMode }
function execShell(verb, file, options) end

---@param verb string
---@param file string
---@param options? { invokeIdList: boolean, parameters: string, showMode: string }
function execShellWait(verb, file, options) end

---@param string string
---@return string
function expandEnvStrings(string) end

---@param WindowClass string
---@param options? { title: string, parent: any, childAfter: any }
---@return any
function findWindow(WindowClass, options) end

---@param filespec string
---@param options? { nonFatal: boolean, keepAttributes: boolean, recursive: boolean, exclude: string[] }
function file(filespec, options) end

---@param ini_file string
function flushIni(ini_file) end

---@param file string
---@param options? { nonFatal: boolean, recursive: boolean, exclude: string[] }
function reserveFile(file, options) end

---@param dialog any
---@param item_id integer
---@return any
function getDlgItem(dialog, item_id) end

---@param path_or_file string
---@param options? { short: boolean }
---@return string
function getFullPathName(path_or_file, options) end

---@param base_dir? string
---@return string
function getTempFileName(base_dir) end

---@param knownfolderid string
---@return string
function getKnownFolderPath(knownfolderid) end

---@param field installua.Field
---@return integer
function getWinVer(field) end

---@param address integer
---@param size integer
---@return string
function readMemory(address, size) end

function hideWindow() end

---@return boolean
function aborted() end

---@return boolean
function errors() end

---@param filename string
---@return boolean
function fileExists(filename) end

---@return boolean
function rebootFlag() end

---@return boolean
function silent() end

---@return boolean
function rtlLanguage() end

---@param hwnd any
---@return boolean
function isWindow(hwnd) end

function os.exit() end

---@param ini_file string
---@param section string
---@param entry_name string
---@return string
function readIniStr(ini_file, section, entry_name) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry string
---@return integer
function readRegDword(rootkey, subkey, entry) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry string
---@return string
function readRegStr(rootkey, subkey, entry) end

---@param name string
---@return string
function readEnvStr(name) end

function reboot() end

---@param dll_path_on_target_dll string
---@param entrypoint_symbol? string
function regDll(dll_path_on_target_dll, entrypoint_symbol) end

---@param source_file string
---@param destination_file string
---@param options? { rebootOk: boolean }
function rename(source_file, destination_file, options) end

---@param directory_name string
---@param options? { recursive: boolean, rebootOk: boolean }
function rmDir(directory_name, options) end

---@param filename string
---@return string
function searchPath(filename) end

---@param insttype_index string
---@param text string
function instTypes.setText(insttype_index, text) end

---@param insttype_index string
---@return string
function instTypes.getText(insttype_index) end

---@param false_or_true installua.Falseortrue
function setAutoClose(false_or_true) end

---@param bitmap_bmp string
---@param options? { imgId: integer, resizeToFit: boolean }
function setBrandingImage(bitmap_bmp, options) end

---@param hide_or_show installua.Hideorshow
function setDetailsView(hide_or_show) end

---@param none_or_listonly_or_textonly_or_both_or_lastused installua.Noneorlistonlyortextonlyorbothorlastused
function setDetailsPrint(none_or_listonly_or_textonly_or_both_or_lastused) end

function setErrors() end

---@param error_level integer
function setErrorLevel(error_level) end

---@return integer
function getErrorLevel() end

---@param file string
---@param attribute installua.Attribute
function setFileAttributes(file, attribute) end

---@param output_path string
function setOutPath(output_path) end

---@param true_or_false installua.Trueorfalse
function setRebootFlag(true_or_false) end

---@return string
function getRegView() end

---@param _32_or_64_or_default_or_lastused installua.32or64ordefaultorlastused
function setRegView(_32_or_64_or_default_or_lastused) end

---@return boolean
function altRegView() end

---@return string
function getShellVarContext() end

---@param all_or_current_or_lastused installua.Allorcurrentorlastused
function setShellVarContext(all_or_current_or_lastused) end

---@return boolean
function shellVarContextAll() end

---@param silent_or_normal installua.Silentornormal
function setSilent(silent_or_normal) end

---@param sleep_time_in_ms integer
function sleep(sleep_time_in_ms) end

---@param str string
---@return integer
function string.len(str) end

---@param dll_path_on_target_dll string
function unRegDll(dll_path_on_target_dll) end

---@param ini_file string
---@param section_name string
---@param entry_name string
---@param new_value string
function writeIniStr(ini_file, section_name, entry_name, new_value) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry_name string
---@param hex_string_like_12848412AB string
function writeRegBin(rootkey, subkey, entry_name, hex_string_like_12848412AB) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry_name string
---@param hex_string_like_660000000000 string
function writeRegMultiStr(rootkey, subkey, entry_name, hex_string_like_660000000000) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry_name string
---@param new_value_dword integer|string
function writeReg(rootkey, subkey, entry_name, new_value_dword) end

---@param rootkey installua.RootKey
---@param subkey string
---@param entry_name string
---@param new_value_string string
function writeRegExpandStr(rootkey, subkey, entry_name, new_value_string) end

---@param rootkey any
---@param subkey string
---@param entry_name string
---@param hex_data? string
function writeRegNone(rootkey, subkey, entry_name, hex_data) end

---@param uninstall_exe_name string
function writeUninstaller(uninstall_exe_name) end

---@param on_or_off installua.Onoroff
function lockWindow(on_or_off) end

--------------------------------------------------------------------------------
-- Predefined NSIS constants, as ordinary read-only globals (§15.1). A `$` in a
-- literal is an error; these are joined with `..` instead.
--------------------------------------------------------------------------------

---@type string
INSTDIR = nil

---@type string
OUTDIR = nil

---@type string
PROGRAMFILES = nil

---@type string
PROGRAMFILES64 = nil

---@type string
COMMONFILES = nil

---@type string
DESKTOP = nil

---@type string
STARTMENU = nil

---@type string
SMPROGRAMS = nil

---@type string
APPDATA = nil

---@type string
LOCALAPPDATA = nil

---@type string
TEMP = nil

---@type string
WINDIR = nil

---@type string
SYSDIR = nil

---@type string
EXEDIR = nil

---@type string
EXEPATH = nil

---@type string
EXEFILE = nil

---@type string
PLUGINSDIR = nil

---@type integer
LANGUAGE = nil

---@type any
HWNDPARENT = nil

---@type any
HKLM = nil

---@type any
HKCU = nil

---@type any
HKCR = nil

---@type any
HKU = nil

---@type any
HKCC = nil

---@type any
SHCTX = nil

