---@meta

-- Generated by `installua stubs` from this project's own sources.
--
-- `include` is frontend-only, so `lua-language-server` cannot follow it and
-- every name an included file contributes would be an unknown global (§15.28).
-- Regenerate after adding a `func` or a global.

