//! `LANGUAGE.md`, generated: one row per NSIS command, status first.
//!
//! The document it writes is a correspondence table and nothing else — the
//! `-CMDHELP` line on one side, the Installua that emits it on the other. Every
//! cell is read from the joined table, so the doc cannot claim a command is
//! exposed after the row that exposed it is deleted, which is the failure mode
//! a hand-written correspondence table has and §14 refuses everywhere else.
//!
//! The three statuses are the seven buckets, projected:
//!
//! | Status | Buckets | Reading |
//! | --- | --- | --- |
//! | ✅ | `exposed`, `attribute`, `lowering-target`, `language` | something in Installua emits it today |
//! | ⚠️ | `todo` | the backlog, with its reason |
//! | ❌ | `rejected`, `directive` | deliberately has no Installua spelling |
//!
//! The projection is total and mechanical on purpose: a status nobody has to
//! choose is a status nobody can forget to update.

use super::{Class, Instruction, Param, Rep, table};
use crate::types::Ty;

/// The whole document. `snapshot` is `tables/cmdhelp-3.12.txt`, read for the
/// syntax lines themselves — the join keeps a command's *shape*, not the text
/// `makensis` printed, and the text is what column two is.
pub fn language(snapshot: &str) -> String {
    let mut rows: Vec<(&'static Instruction, String)> = table()
        .iter()
        .map(|entry| (entry, syntax(snapshot, entry.nsis)))
        .collect();
    rows.sort_by_key(|(entry, _)| entry.nsis.to_ascii_lowercase());

    let mut out = String::new();
    out.push_str(&header());
    out.push_str("| Status | NSIS | Installua |\n| --- | --- | --- |\n");
    for (entry, syntax) in rows {
        out.push_str(&format!(
            "| {} | {} | {} |\n",
            status(entry.class),
            code(&syntax),
            installua(entry),
        ));
    }
    out
}

fn header() -> String {
    let counts: Vec<String> = super::census()
        .iter()
        .map(|(bucket, count)| format!("{count} {bucket}"))
        .collect();

    format!(
        "<!-- Generated by `cargo run -q -- language tables/cmdhelp-3.12.txt > LANGUAGE.md`.\n\
         \x20    Do not edit: every cell comes from `src/table/overlay.rs`. -->\n\
         \n\
         # Installua ↔ NSIS\n\
         \n\
         Every command `makensis {} -CMDHELP` prints, beside the Installua that emits it.\n\
         \n\
         - ✅ implemented — Installua can write it today\n\
         - ⚠️ needs design or a decision — the backlog, reason in `installua coverage`\n\
         - ❌ no Installua spelling — rejected on purpose, or preprocessor (§2)\n\
         \n\
         `x = f(…)` means the call has an output; `a, b = f(…)` means two. Square\n\
         brackets are optional positions, `…` a repeated one, `{{ … }}` an options table.\n\
         \n\
         {}.\n\
         \n",
        super::generated::VERSION,
        counts.join(", "),
    )
}

fn status(class: Class) -> &'static str {
    match class {
        Class::Exposed | Class::Attribute(_) | Class::LoweringTarget(_) | Class::Language(_) => {
            "✅"
        }
        Class::Todo(_) => "⚠️",
        Class::Rejected(_) | Class::Directive => "❌",
    }
}

/// The `-CMDHELP` line for one command. The indented continuations are enum
/// members and stay out — the Installua side already spells them — with one
/// exception: a line ending in `|` is a *wrapped* alternation (`File`, and only
/// `File` in 3.12), and half of an alternation is a lie rather than a summary.
fn syntax(snapshot: &str, nsis: &str) -> String {
    let mut lines = snapshot
        .lines()
        .filter(|line| !line.starts_with('#'))
        .skip_while(|line| {
            line.starts_with(char::is_whitespace)
                || line.split_once(char::is_whitespace).map(|(name, _)| name) != Some(nsis)
                    && *line != nsis
        });

    let Some(first) = lines.next() else {
        return nsis.to_string();
    };
    let mut out = first.trim_end().to_string();
    while out.ends_with('|') {
        match lines.next() {
            Some(next) => {
                out.push(' ');
                out.push_str(next.trim());
            }
            None => break,
        }
    }
    out
}

/// Column three: what a user writes. An `Exposed` row is reconstructed from the
/// parameter model rather than from its example, because the examples are
/// multi-line programs and this is one cell.
fn installua(entry: &Instruction) -> String {
    match entry.class {
        // A row with a `Kind::Bound` position is reached through a name rather
        // than called (§13), so the cell is the assignment a user writes:
        // `handle.text = …` where the value goes in, `x = handle.text` where it
        // comes back.
        Class::Exposed if entry.bound() => match entry.installua {
            Some(name) if entry.outputs().next().is_some() => code(&format!("x = {name}")),
            Some(name) => code(&format!("{name} = …")),
            None => "—".to_string(),
        },
        Class::Exposed => code(&call(entry)),
        Class::Attribute(_) => match entry.installua {
            Some(field) => code(&format!("{field} = …")),
            None => "—".to_string(),
        },
        Class::LoweringTarget(instead) | Class::Language(instead) => instead.to_string(),
        Class::Rejected(why) | Class::Todo(why) => why.to_string(),
        Class::Directive => "—".to_string(),
    }
}

fn call(entry: &Instruction) -> String {
    let name = entry.installua.unwrap_or(entry.nsis);
    let mut args = String::new();
    let mut optional = 0usize;

    // `f:close` is a method, so the handle NSIS takes as its first argument is
    // the receiver and not an argument at all (§8's typed handles). The colon
    // in the spelling is what says so.
    let method = name.contains(':');
    let surface = entry
        .surface()
        .filter(|param| !(method && param.shape.var))
        .collect::<Vec<_>>();

    for (index, param) in surface.into_iter().enumerate() {
        if !param.required() {
            args.push('[');
            optional += 1;
        }
        if index > 0 {
            args.push_str(", ");
        }
        args.push_str(&argument(param));
        if param.shape.rep == Rep::Many {
            args.push_str(", …");
        }
    }
    // The trailing `{ … }`, when there is one to write. Not `!options.is_empty()`
    // — a row can carry a flag the surface does not offer, and a cell claiming
    // an options table nobody can fill is the drift this file exists to avoid.
    if entry.takes_options() {
        if args.is_empty() {
            args.push_str("[{ … }]");
        } else {
            args.push_str("[, { … }]");
        }
    }
    args.push_str(&"]".repeat(optional));

    format!("{}{name}({args})", bindings(entry))
}

/// One argument's name. `-CMDHELP` names an enum position after its own
/// members — `32_or_64_or_default_or_lastused` — which column two already
/// prints in full, so the name says what the position *is* instead: `mode`, or
/// `enabled` where §15.17 made the two-valued enum a boolean.
fn argument(param: &Param) -> String {
    // An index position the *surface* writes as a `string` is the name the
    // compiler resolves the index from, and printing `insttypeIndex` would say
    // the opposite of §13. `instTypes.setText("Full", …)` takes a name.
    if param.ty == Ty::Str && param.shape.name.ends_with("_index") {
        return "name".to_string();
    }
    let members = param.members();
    let listed = !members.is_empty() && param.shape.name == members.join("_or_").to_lowercase();
    if listed {
        return match param.ty {
            Ty::Bool => "enabled".to_string(),
            _ => "mode".to_string(),
        };
    }
    lower_camel(param.shape.name)
}

/// The `x = ` prefix. A predicate has no output register — its value is the
/// branch — so it binds a `bool` and reads the same at the call site.
fn bindings(entry: &Instruction) -> String {
    let outputs: Vec<&Param> = entry.outputs().collect();
    let names: Vec<String> = match (entry.predicate, outputs.len()) {
        (true, _) | (_, 1) => vec!["x".to_string()],
        (_, 0) => return String::new(),
        (_, many) => outputs
            .iter()
            .enumerate()
            .map(|(index, param)| {
                let name = lower_camel(&param.shape.name.replace("_output", ""));
                if name == "output" || name.is_empty() {
                    format!("x{}", index + 1)
                } else {
                    name
                }
            })
            .take(many)
            .collect(),
    };
    format!("{} = ", names.join(", "))
}

/// `new_position_output` → `newPosition`. The `-CMDHELP` names are snake_case
/// and carry their direction in the name; Installua's are camelCase and carry
/// it in the arity (§15.23).
fn lower_camel(name: &str) -> String {
    let name = name
        .trim_end_matches("_output")
        .trim_start_matches("output_")
        .replace("user_var: ", "");
    let mut out = String::new();
    let mut upper = false;
    for character in name.chars() {
        match character {
            '_' => upper = true,
            _ if upper => {
                out.extend(character.to_uppercase());
                upper = false;
            }
            _ => out.push(character),
        }
    }
    if out.is_empty() { "x".to_string() } else { out }
}

/// A code span. A `|` needs escaping inside a table cell even there, and
/// `-CMDHELP` is full of them.
fn code(text: &str) -> String {
    format!("`{}`", text.replace('|', "\\|"))
}
