#!/usr/bin/env python3
"""Prototype of the generated selene std (§1). Phase 0 only — the real one is
`installua stubs`' sibling, generated from the overlay in Phase 5.

Two findings are baked in here and both are load-bearing:

  * selene wants YAML, not the TOML §1 assumed.
  * There is **no `lua54` base std** in selene, and setting `base:` *overwrites*
    `lua_versions:` rather than merging with it ("Intentionally not a merge" —
    selene-lib/src/standard_library/mod.rs). So a std with any base parses at
    that base's Lua version, and `local X <const> = …` is a parse error.
    The generated std therefore declares **no base** and lists the whole
    surface itself, which §5's wholesale whitelist makes cheap anyway.
"""

import io

# The Lua stdlib §5 keeps. No base std, so what is not here does not exist —
# which is the mechanism that retires the `removed: true` list entirely.
KEPT = {
    "string.upper": [("string", True)],
    "string.lower": [("string", True)],
    "string.len": [("string", True)],
    "string.sub": [("string", True), ("number", True), ("number", False)],
    "string.rep": [("string", True), ("number", True)],
    "string.format": [("string", True)],  # variadic; see VARIADIC below
    "math.abs": [("number", True)],
    "math.max": [("number", True)],
    "math.min": [("number", True)],
    "tostring": [("any", True)],
    "tonumber": [("any", True)],
}
VARIADIC = {"string.format", "math.max", "math.min"}

# §5 rejections that a *reader* will still reach for. Without a base these are
# already undefined, but an explicit `deprecated` entry is what lets the
# diagnostic name a replacement (§14: "every rejection names its replacement").
REJECTED = {
    "string.gsub": (
        [("string", True), ("string", True), ("string", True)],
        "Lua patterns have no NSIS lowering",
        "string.replace(%1, %2, %3)",
    ),
    "string.find": (
        [("string", True), ("string", True)],
        "Lua patterns have no NSIS lowering",
        "string.indexOf(%1, %2)",
    ),
    "math.floor": ([("number", True)], "there are no floats; `//` is already integer division", "%1"),
    "pcall": ([("any", True)], "NSIS has no exceptions; check `errors()` instead", "errors()"),
    "require": ([("string", True)], "use `include` for source, `import` for NSIS headers", "include(%1)"),
    "print": ([("any", True)], "the installer log is `detailPrint`", "detailPrint(%1)"),
    "pairs": ([("any", True)], "there is no runtime heap; iterate a directory with `findFiles`", "findFiles(%1)"),
    "ipairs": ([("any", True)], "there is no runtime heap; iterate a directory with `findFiles`", "findFiles(%1)"),
    "setmetatable": ([("any", True), ("any", True)], "there are no metatables", ""),
}

# The Installua API, as globals (§15.13).
API = {
    "attributes": [("table", True)],
    "installer": [("table", True)],
    "uninstaller": [("table", True)],
    "languages": [("table", True)],
    "section": [("string", True), ("function", True)],
    "onInit": [("function", True)],
    "detailPrint": [("string", True)],
    "setOutPath": [("string", True)],
    "file": [("string", True)],
    "abort": [("string", False)],
    "messageBox": [("table", True)],
    "import": [("string", True)],
    "plugin": [("string", True)],
    "raw": [("string", True)],
}

# NSIS constants, as read-only globals (§15.1).
CONSTANTS = ["INSTDIR", "DESKTOP", "PROGRAMFILES64", "TEMP", "APPDATA"]


def args_block(out, args, indent, variadic=False):
    out.write("%sargs:\n" % indent)
    for ty, required in args:
        out.write("%s  - type: %s\n" % (indent, ty))
        if not required:
            out.write("%s    required: false\n" % indent)
    if variadic:
        out.write("%s  - type: ...\n" % indent)


def main():
    out = io.StringIO()
    out.write("# GENERATED by gen_selene_std.py — Phase 0 prototype, do not edit.\n")
    out.write("# No `base:`; see the module docstring for why.\n")
    out.write("lua_versions:\n  - lua54\n")
    out.write("name: installua\n")
    out.write("globals:\n")

    for name, args in sorted(KEPT.items()):
        out.write("  %s:\n" % name)
        args_block(out, args, "    ", name in VARIADIC)

    for name, (args, message, replace) in sorted(REJECTED.items()):
        out.write("  %s:\n" % name)
        args_block(out, args, "    ")
        out.write("    deprecated:\n")
        out.write("      message: %r\n" % message)
        if replace:
            out.write("      replace:\n        - %r\n" % replace)

    for name, args in sorted(API.items()):
        out.write("  %s:\n" % name)
        args_block(out, args, "    ")

    for name in CONSTANTS:
        out.write("  %s:\n    property: read-only\n" % name)

    open("installua.yml", "w").write(out.getvalue())


if __name__ == "__main__":
    main()
