-- Generated by tests/overlay.rs from the overlay's own `Attribute` rows.
attributes {
	caption = "caption",
	crcCheck = true,
	allowRootDirInstall = true,
	fileBufSize = 1,
	icon = "assets/icon.ico",
	installDirRegKey = { root = HKCR, key = "key.out", name = "name" },
	installDir = "installDir.out",
	license = "assets/license.txt",
	name = "name",
	outFile = "outFile.out",
	compressor = "zlib",
	dateSave = true,
	showInstDetails = "hide",
	showUninstDetails = "hide",
	silentInstall = "normal",
	silentUninstall = "normal",
	cpu = "x86",
	peDllCharacteristics = { add = 1, remove = 1 },
	peSubsysVer = "5.1",
	requestExecutionLevel = "none",
	manifestDpiAware = true,
	manifestDpiAwareness = "manifestDpiAwareness",
	manifestLongPathAware = true,
	manifestMaxVersionTested = "10.0.19041.0",
	manifestDisableWindowFiltering = true,
	manifestGdiScaling = true,
	allowSkipFiles = true,
}

installer {
	section("Core", function()
		detailPrint("installing")
	end),
}
