-- Generated by tests/overlay.rs from the overlay's own examples.
attributes {
	name = "Overlay examples",
	outFile = "examples.exe",
	unicode = true,
	brandingImage = { edge = "top", size = "20u" },
}

local handle = section("Addressed", function()
	detailPrint("the section the examples below address")
end)

installer {
	installTypes = { "Full", "Minimal" },
	handle,
	section("Abort", function()
		abort("stopped")
	end),
	section("BringToFront", function()
		bringToFront()
	end),
	section("ClearErrors", function()
		clearErrors()
	end),
	section("GetDLLVersion", function()
		local high, low = getDllVersion(INSTDIR .. "/shell.dll")
		detailPrint(high .. "." .. low)
	end),
	section("GetDLLVersionLocal", function()
		local high, low = getDllVersionLocal("assets/version.dll")
		detailPrint(high .. "." .. low)
	end),
	section("GetFileTime", function()
		local high, low = getFileTime(INSTDIR .. "/app.exe")
		detailPrint(high .. " " .. low)
	end),
	section("GetFileTimeLocal", function()
		local high, low = getFileTimeLocal("assets/icon.ico")
		detailPrint(high .. " " .. low)
	end),
	section("CopyFiles", function()
		copyFiles(INSTDIR .. "/data", INSTDIR .. "/backup")
	end),
	section("CreateDirectory", function()
		createDirectory(INSTDIR .. "/logs")
	end),
	section("CreateShortcut", function()
		createShortcut(DESKTOP .. "/App.lnk", INSTDIR .. "/app.exe", { comment = "Launch App" })
	end),
	section("DeleteINISec", function()
		deleteIniSection(INSTDIR .. "/app.ini", "Settings")
	end),
	section("DeleteINIStr", function()
		deleteIniStr(INSTDIR .. "/app.ini", "Settings", "Path")
	end),
	section("DeleteRegKey", function()
		deleteRegKey(HKLM, "Software/Example")
	end),
	section("DeleteRegValue", function()
		deleteRegValue(HKLM, "Software/Example", "Path")
	end),
	section("Delete", function()
		delete(INSTDIR .. "/old.txt", { rebootOk = true })
	end),
	section("DetailPrint", function()
		detailPrint("installing")
	end),
	section("GetInstDirError", function()
		local why = getInstDirError()
		detailPrint("instdir " .. why)
	end),
	section("EnumRegKey", function()
		local key = enumRegKey(HKLM, "Software/Example", 0)
		detailPrint(key)
	end),
	section("EnumRegValue", function()
		local entry = enumRegValue(HKLM, "Software/Example", 0)
		detailPrint(entry)
	end),
	section("Exec", function()
		exec(INSTDIR .. "/app.exe /S")
	end),
	section("ExecWait", function()
		local code = execWait(INSTDIR .. "/app.exe /S")
		detailPrint("exit " .. code)
	end),
	section("ExecShell", function()
		execShell("open", "https://example.invalid", { showMode = "SW_HIDE" })
	end),
	section("ExecShellWait", function()
		execShellWait("open", INSTDIR .. "/readme.txt")
	end),
	section("ExpandEnvStrings", function()
		local temp = expandEnvStrings("%TEMP%")
		detailPrint(temp)
	end),
	section("FindWindow", function()
		local window = findWindow("Notepad")
		if isWindow(window) then
			detailPrint("already running")
		end
	end),
	section("File", function()
		file("assets/icon.ico", { exclude = { "*.tmp", "*.log" } })
	end),
	section("FlushINI", function()
		flushIni(INSTDIR .. "/app.ini")
	end),
	section("FileClose", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:close()
	end),
	section("FileOpen", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:close()
	end),
	section("FileRead", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		for line in lines(f) do detailPrint(line) end
		f:close()
	end),
	section("FileWrite", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:write("done")
		f:close()
	end),
	section("FileReadByte", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		local b = f:readByte()
		detailPrint("byte " .. b)
		f:close()
	end),
	section("FileWriteByte", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:writeByte(65)
		f:close()
	end),
	section("FileReadUTF16LE", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		local line = f:readUtf16Le()
		detailPrint(line)
		f:close()
	end),
	section("FileWriteUTF16LE", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:writeUtf16Le("done", { bom = true })
		f:close()
	end),
	section("FileReadWord", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		local w = f:readWord()
		detailPrint("word " .. w)
		f:close()
	end),
	section("FileWriteWord", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:writeWord(1024)
		f:close()
	end),
	section("FileSeek", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		local size = f:seek(0, "END")
		detailPrint("size " .. size)
		f:close()
	end),
	section("GetDlgItem", function()
		local cancel = getDlgItem(HWNDPARENT, 2)
		cancel.enabled = false
	end),
	section("GetFullPathName", function()
		local full = getFullPathName(INSTDIR .. "/app.exe")
		detailPrint(full)
	end),
	section("GetTempFileName", function()
		local scratch = getTempFileName()
		detailPrint(scratch)
	end),
	section("GetKnownFolderPath", function()
		local downloads = getKnownFolderPath("{374DE290-123F-4565-9164-39C4925E467B}")
		detailPrint(downloads)
	end),
	section("GetWinVer", function()
		if getWinVer("MAJOR") >= 10 then detailPrint("modern") end
	end),
	section("ReadMemory", function()
		local bytes = readMemory(0, 4)
		detailPrint(bytes)
	end),
	section("HideWindow", function()
		hideWindow()
	end),
	section("IfAbort", function()
		if aborted() then detailPrint("cancelled") end
	end),
	section("IfErrors", function()
		clearErrors()
		if errors() then detailPrint("failed") end
	end),
	section("IfFileExists", function()
		if fileExists(INSTDIR .. "/app.exe") then detailPrint("present") end
	end),
	section("IfRebootFlag", function()
		if rebootFlag() then detailPrint("a restart is needed") end
	end),
	section("IfSilent", function()
		if silent() then detailPrint("quiet") end
	end),
	section("IfRtlLanguage", function()
		if rtlLanguage() then detailPrint("right to left") end
	end),
	section("IsWindow", function()
		local window = findWindow("Notepad")
		if isWindow(window) then
			detailPrint("still open")
		end
	end),
	section("MessageBox", function()
		messageBox { text = "Restart now?", buttons = "YESNO", silentAnswer = "NO" }
	end),
	section("Quit", function()
		os.exit()
	end),
	section("ReadINIStr", function()
		local port = readIniStr(INSTDIR .. "/app.ini", "Settings", "Port")
		detailPrint(port)
	end),
	section("ReadRegDWORD", function()
		local build = readRegDword(HKLM, "Software/Example", "Build")
		detailPrint("build " .. build)
	end),
	section("ReadRegStr", function()
		local path = readRegStr(HKLM, "Software/Example", "Path")
		detailPrint(path)
	end),
	section("ReadEnvStr", function()
		local temp = readEnvStr("TEMP")
		detailPrint(temp)
	end),
	section("Reboot", function()
		reboot()
	end),
	section("RegDLL", function()
		regDll(INSTDIR .. "/shell.dll")
	end),
	section("Rename", function()
		rename(INSTDIR .. "/old.txt", INSTDIR .. "/new.txt")
	end),
	section("RMDir", function()
		rmDir(INSTDIR, { recursive = true, rebootOk = true })
	end),
	section("SearchPath", function()
		local found = searchPath("notepad.exe")
		detailPrint(found)
	end),
	section("SectionSetFlags", function()
		handle.selected = false
	end),
	section("SectionGetFlags", function()
		if handle.selected then
			detailPrint("the addressed section is ticked")
		end
	end),
	section("SectionSetInstTypes", function()
		handle.installTypes = { "Minimal" }
	end),
	section("SectionGetText", function()
		local label = handle.text
		detailPrint(label)
	end),
	section("SectionSetText", function()
		handle.text = "Core files"
	end),
	section("SectionGetSize", function()
		local kilobytes = handle.size
		detailPrint("charging " .. kilobytes .. " KB")
	end),
	section("SectionSetSize", function()
		handle.size = 4096
	end),
	section("GetCurInstType", function()
		local chosen = currentInstType
		detailPrint("installing " .. chosen)
	end),
	section("SetCurInstType", function()
		currentInstType = "Minimal"
	end),
	section("InstTypeSetText", function()
		instTypes.setText("Full", "Everything")
	end),
	section("InstTypeGetText", function()
		local label = instTypes.getText("Full")
		detailPrint(label)
	end),
	section("SetAutoClose", function()
		setAutoClose("true")
	end),
	section("SetBrandingImage", function()
		setBrandingImage("assets/icon.ico", { imgId = 1032, resizeToFit = true })
	end),
	section("SetDetailsView", function()
		setDetailsView("show")
	end),
	section("SetDetailsPrint", function()
		setDetailsPrint("listonly")
	end),
	section("SetErrors", function()
		setErrors()
	end),
	section("SetErrorLevel", function()
		setErrorLevel(2)
	end),
	section("GetErrorLevel", function()
		local level = getErrorLevel()
		detailPrint("level " .. level)
	end),
	section("SetFileAttributes", function()
		setFileAttributes(INSTDIR .. "/readme.txt", "READONLY")
	end),
	section("SetOutPath", function()
		setOutPath(INSTDIR)
	end),
	section("SetRebootFlag", function()
		setRebootFlag("true")
	end),
	section("GetRegView", function()
		local view = getRegView()
		detailPrint(view)
	end),
	section("SetRegView", function()
		setRegView("64")
	end),
	section("IfAltRegView", function()
		if altRegView() then detailPrint("the other view") end
	end),
	section("GetShellVarContext", function()
		local context = getShellVarContext()
		detailPrint(context)
	end),
	section("SetShellVarContext", function()
		setShellVarContext("all")
	end),
	section("IfShellVarContextAll", function()
		if shellVarContextAll() then detailPrint("all users") end
	end),
	section("Sleep", function()
		sleep(500)
	end),
	section("StrLen", function()
		local n = string.len("abc")
		detailPrint("len " .. n)
	end),
	section("UnRegDLL", function()
		unRegDll(INSTDIR .. "/shell.dll")
	end),
	section("WriteINIStr", function()
		writeIniStr(INSTDIR .. "/app.ini", "Settings", "Path", INSTDIR)
	end),
	section("WriteRegBin", function()
		writeRegBin(HKLM, "Software/Example", "Blob", "12848412AB")
	end),
	section("WriteRegMultiStr", function()
		writeRegMultiStr(HKLM, "Software/Example", "List", "660000000000")
	end),
	section("WriteRegDWORD", function()
		writeReg(HKLM, "Software/Example", "Build", 42)
	end),
	section("WriteRegStr", function()
		writeReg(HKLM, "Software/Example", "Path", INSTDIR)
	end),
	section("WriteRegExpandStr", function()
		writeRegExpandStr(HKLM, "Software/Example", "Data", "%APPDATA%/Example")
	end),
	section("WriteRegNone", function()
		writeRegNone(HKLM, "Software/Example", "Marker")
	end),
	section("WriteUninstaller", function()
		writeUninstaller(INSTDIR .. "/uninstall.exe")
	end),
	section("LockWindow", function()
		lockWindow("on")
	end),
}

uninstaller {
	section("Uninstall", function()
		rmDir(INSTDIR)
	end),
}
