-- Generated by tests/overlay.rs from the overlay's own examples.
attributes {
	name = "Overlay examples",
	outFile = "examples.exe",
	unicode = true,
}

installer {
	section("Abort", function()
		abort("stopped")
	end),
	section("ClearErrors", function()
		clearErrors()
	end),
	section("CreateDirectory", function()
		createDirectory(INSTDIR .. "/logs")
	end),
	section("CreateShortcut", function()
		createShortcut(DESKTOP .. "/App.lnk", INSTDIR .. "/app.exe")
	end),
	section("DeleteRegKey", function()
		deleteRegKey(HKLM, "Software/Example")
	end),
	section("Delete", function()
		delete(INSTDIR .. "/old.txt")
	end),
	section("DetailPrint", function()
		detailPrint("installing")
	end),
	section("File", function()
		file("assets/icon.ico")
	end),
	section("FileClose", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:close()
	end),
	section("FileOpen", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:close()
	end),
	section("FileRead", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "r")
		for line in lines(f) do detailPrint(line) end
		f:close()
	end),
	section("FileWrite", function()
		local f = fileOpen(INSTDIR .. "/log.txt", "w")
		f:write("done")
		f:close()
	end),
	section("IfErrors", function()
		clearErrors()
		if errors() then detailPrint("failed") end
	end),
	section("IfFileExists", function()
		if fileExists(INSTDIR .. "/app.exe") then detailPrint("present") end
	end),
	section("IfSilent", function()
		if silent() then detailPrint("quiet") end
	end),
	section("MessageBox", function()
		messageBox("finished")
	end),
	section("Quit", function()
		os.exit()
	end),
	section("ReadRegStr", function()
		local path = readRegStr(HKLM, "Software/Example", "Path")
		detailPrint(path)
	end),
	section("RMDir", function()
		rmDir(INSTDIR)
	end),
	section("SetOutPath", function()
		setOutPath(INSTDIR)
	end),
	section("Sleep", function()
		sleep(500)
	end),
	section("StrLen", function()
		local n = string.len("abc")
		detailPrint("len " .. n)
	end),
	section("WriteRegDWORD", function()
		writeReg(HKLM, "Software/Example", "Build", 42)
	end),
	section("WriteRegStr", function()
		writeReg(HKLM, "Software/Example", "Path", INSTDIR)
	end),
	section("WriteUninstaller", function()
		writeUninstaller(INSTDIR .. "/uninstall.exe")
	end),
}
