-- Generated by tests/overlay.rs from the overlay's own `Attribute` rows.
attributes {
	caption = "caption",
	crcCheck = true,
	allowRootDirInstall = true,
	fileBufSize = 1,
	icon = "assets/icon.ico",
	installDir = "installDir.out",
	license = "assets/license.txt",
	name = "name",
	outFile = "outFile.out",
	compressor = "zlib",
	dateSave = true,
	showInstDetails = "hide",
	showUninstDetails = "hide",
	silentInstall = "normal",
	silentUninstall = "normal",
	cpu = "x86",
	requestExecutionLevel = "none",
	allowSkipFiles = true,
}

installer {
	section("Core", function()
		detailPrint("installing")
	end),
}
