//! `installua stubs` and `installua init`: the editor's half of §1.
//!
//! Installua's API is globals, so `lua-language-server` sees `installer`,
//! `section` and `detailPrint` as undefined and lights up every source file
//! before it has done anything wrong. The wrong fix is
//! `Lua.diagnostics.globals`, which silences the warning and gives up hover,
//! completion, arity checking and go-to-definition on exactly the names that
//! need them — the entire reason for insisting on valid Lua.
//!
//! The fix is generated: a LuaCATS `---@meta` file ([`meta`]) declaring the
//! API, a selene std ([`selene_std`]) naming a replacement for every §5
//! rejection, and a `.luarc.json` wiring them up ([`luarc`]). All three come
//! from the same tables the compiler checks against ([`crate::table`],
//! [`crate::builtins`]), because a hand-maintained second copy drifts — which
//! is nsL's failure mode in a new place (§9-5).
//!
//! **Two tools, two halves.** LuaLS has no "poison this name" annotation, so
//! the names it keeps and §5 rejects — `pcall`, `math.floor`, `string.gsub` —
//! cannot be removed from the stub; they are selene's `deprecated` entries
//! instead, each naming its replacement (§2). One generator, so the two halves
//! cannot disagree about what is rejected.

use std::collections::BTreeSet;
use std::fmt::Write;

use crate::builtins;
use crate::lower::control;
use crate::table::{self, Class, Param};
use crate::types::Ty;

/// `.installua/meta/installua.lua`: the `---@meta` file.
pub fn meta() -> String {
    let mut out = String::from(
        "---@meta\n\
         \n\
         -- Generated by `installua stubs`. Do not edit.\n\
         --\n\
         -- `---@meta` marks this file as definitions-only: it contributes no runtime\n\
         -- code and its own contents are not diagnosed. Everything here comes from the\n\
         -- same table the compiler checks against (§15.23), so the editor and the\n\
         -- compiler cannot disagree about what exists.\n\n",
    );

    out.push_str(&aliases());
    out.push_str(&blocks());
    out.push_str(&declarations());
    out.push_str(&controls());
    out.push_str(&instructions());
    out.push_str(&constants());
    out
}

/// The enum members, as `---@alias`es of string literals.
///
/// This is the shape that buys completion **inside** a string literal, which is
/// where most of an installer's interesting values live — and it is generated
/// from `-CMDHELP`'s own member lists rather than transcribed (§15.23).
fn aliases() -> String {
    let mut out = String::from(
        "--------------------------------------------------------------------------------\n\
         -- Enums, as `---@alias`. An alias of string literals completes *inside* the\n\
         -- quotes, which a plain `string` does not.\n\
         --------------------------------------------------------------------------------\n\n",
    );

    for (name, members, open) in alias_table() {
        let _ = writeln!(out, "---@alias {name}");
        for member in members {
            let _ = writeln!(out, "---| '\"{member}\"'");
        }
        // An **open** enum lists what is worth completing and then admits the
        // rest: `ManifestSupportedOS`'s `{GUID}` is every GUID there is, and an
        // alias that stopped at the seven names would mark a legal one wrong.
        // The literals still complete, because LuaLS offers them first.
        if open {
            let _ = writeln!(out, "---| string");
        }
        out.push('\n');
    }
    out
}

/// The aliases worth naming, and the parameters they belong to.
///
/// Keyed on the *parameter name* rather than on the command, because `openmode`
/// is one idea whether `FileOpen` or a future command asks for it — and because
/// a single catch-all alias would silently give the first enum's members to
/// every other enum, which is a wrong completion rather than a missing one.
fn alias_table() -> Vec<(String, Vec<&'static str>, bool)> {
    let mut aliases: Vec<(String, Vec<&'static str>, bool)> = Vec::new();

    for entry in table::table() {
        // Attributes as well as instructions: `compressor` and
        // `requestExecutionLevel` are enums a user writes into `attributes {}`,
        // and their members are in the same snapshot as everyone else's.
        let named = match entry.class {
            Class::Exposed => None,
            // Only an enum wants one. A `bool` attribute needs none: NSIS's
            // `on|off` is a Lua `true|false` here (§15.16), and an alias of the
            // NSIS spellings would complete the two words this language does not
            // accept.
            Class::Attribute(table::Setting::Enum) => entry.installua,
            // A table's enum parts are named after the *parameter* instead:
            // `installDirRegKey.root` is a registry root, which the `Reg*`
            // instructions already have an alias for, and a second alias with
            // identical members is what this function exists to avoid.
            Class::Attribute(table::Setting::Table(_) | table::Setting::Off { .. }) => None,
            Class::Attribute(_) => continue,
            _ => continue,
        };

        for param in &entry.params {
            if param.members().is_empty() {
                continue;
            }
            let name = match named {
                Some(field) => alias_of(field),
                None => alias_of(param.shape.name),
            };
            if !aliases.iter().any(|(known, _, _)| *known == name) {
                aliases.push((name, param.members().to_vec(), param.open()));
            }
        }
    }

    aliases
}

/// `openmode` ⇒ `installua.OpenMode`, and so does `open_mode`.
///
/// The name is canonicalised first, because `-CMDHELP` spells one parameter two
/// ways — `WriteRegStr rootkey` and `DeleteRegKey root_key` are the same
/// registry root — and two aliases with identical members is the kind of
/// duplication a reader has to check rather than read. [`SPELLINGS`] carries
/// the display form for the compounds a machine cannot split; everything else
/// gets its first letter capitalised.
fn alias_of(name: &str) -> String {
    let canonical: String = name
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .map(|c| c.to_ascii_lowercase())
        .collect();

    let display = SPELLINGS
        .iter()
        .find(|(key, _)| *key == canonical)
        .map(|(_, display)| display.to_string())
        .unwrap_or_else(|| {
            let mut chars = canonical.chars();
            match chars.next() {
                Some(first) => first.to_uppercase().chain(chars).collect(),
                None => String::new(),
            }
        });

    format!("installua.{display}")
}

/// Where the word boundary is in a name `-CMDHELP` wrote without one. Display
/// only: the members always come from the snapshot.
const SPELLINGS: &[(&str, &str)] = &[
    ("rootkey", "RootKey"),
    ("openmode", "OpenMode"),
    ("showmode", "ShowMode"),
    ("hotkey", "HotKey"),
    ("crccheck", "CrcCheck"),
    ("requestexecutionlevel", "ExecutionLevel"),
];

/// The four blocks (§15.10, §15.26).
///
/// The field *names* are the overlay's — an `Attribute` row carries the field
/// path a user writes, which is why `versionInfo.product` is spelled that way
/// there — and the Lua types are here, because a block's value is an expression
/// in a table rather than an argument and the parameter model has nothing to
/// say about it. That is the one place a name is written twice, and
/// `tests/stubs.rs` compiles every field to keep the two honest.
fn blocks() -> String {
    let mut out = String::from(
        "--------------------------------------------------------------------------------\n\
         -- Blocks (§15.10). Field names come from the overlay's `Attribute` rows.\n\
         --------------------------------------------------------------------------------\n\n\
         ---@class (exact) installua.VersionInfo\n\
         ---@field product? string\n\
         ---@field file? string\n\
         ---@field keys? table<string, string|table<string, string>>\n\n\
         ---@class (exact) installua.Attributes\n",
    );

    for (field, ty) in attribute_fields() {
        let optional = if field == "outFile" { "" } else { "?" };
        let _ = writeln!(out, "---@field {field}{optional} {ty}");
    }

    out.push_str(
        "\n---@class (exact) installua.Installer\n\
         ---@field installDir? string\n\
         ---@field icon? string\n\
         ---@field caption? string\n\
         ---@field installTypes? string[]\n\
         ---@field checkBitmap? string\n\
         ---@field installColors? string\n\
         ---@field progressBar? string\n\
         ---@field licenseBkColor? string\n\
         ---@field headerColors? installua.Colors\n\
         ---@field abortPrompt? boolean|{ text?: string, default?: string }\n\
         ---@field autoClose? boolean\n\
         ---@field headerImage? string|boolean|{ file?: string, stretch?: string, rtl?: string|{ file: string, stretch?: string }, right?: boolean, transparentText?: boolean }\n\
         ---@field wizardImage? string|{ file: string, stretch?: string }\n\
         ---@field smallDescriptions? boolean\n\n\
         ---@param options installua.Attributes\n\
         function attributes(options) end\n\n\
         ---@param options installua.Installer\n\
         function installer(options) end\n\n\
         ---@param options installua.Installer\n\
         function uninstaller(options) end\n\n\
         ---@class (exact) installua.Ask\n\
         ---@field title? string\n\
         ---@field info? string\n\
         ---@field allLanguages? boolean\n\
         ---@field alwaysShow? boolean\n\
         ---@field remember? { root: string, key: string, value: string }\n\n\
         ---@class (exact) installua.Languages\n\
         ---@field locales table<string, table<string, string>>\n\
         ---@field ask? installua.Ask\n\n\
         ---@param options installua.Languages\n\
         function languages(options) end\n\n\
         --- The strings `languages {}` declared. A read is `$(name)`, resolved\n\
         --- against `$LANGUAGE` at run time (§15.26).\n\
         ---@type table<string, string>\n\
         lang = {}\n\n",
    );
    out.push_str(PAGES);
    out
}

/// The eight pages (§15.7, §15.32), as a table of constructors rather than a
/// list of names.
///
/// `page.directory { … }` and not `page("Directory", … )` because the set is
/// **closed**: MUI2 picks seven of these and a user picks a section's name, so a
/// member completes where a string cannot. That is also what buys a per-page
/// field class — the settings differ by page, and one `page(name, options)`
/// signature would have to take the union of all of them.
///
/// Hand-written, like `installua.Installer` above and for the same reason: a
/// block's value is an expression in a table rather than an argument, and the
/// parameter model has nothing to say about it. `tests/stubs.rs` compiles every
/// field against the compiler to keep the two honest.
const PAGES: &str = "\
-- The hooks every page has, and the header strip five of the eight draw into.\n\
-- `welcome` and `finish` are full-window pages with no header, which is why\n\
-- they inherit the bare class and the other six inherit the headed one.\n\
---@class (exact) installua.Page\n\
---@field pre? fun()\n\
---@field show? fun()\n\
---@field leave? fun()\n\
\n\
---@class (exact) installua.Page.Headed : installua.Page\n\
---@field headerText? string\n\
---@field headerSubText? string\n\
\n\
---@class (exact) installua.Page.Welcome : installua.Page\n\
---@field title? string|{ text: string, lines: integer }\n\
---@field text? string\n\
---@field destroyed? fun()\n\
\n\
---@class (exact) installua.Page.License : installua.Page.Headed\n\
---@field file string\n\
---@field subCaption? string\n\
---@field topText? string\n\
---@field bottomText? string\n\
---@field button? string\n\
---@field checkbox? string\n\
---@field radioButtons? { accept?: string, decline?: string }\n\
\n\
---@class (exact) installua.Page.Components : installua.Page.Headed\n\
---@field subCaption? string\n\
---@field topText? string\n\
---@field instTypeText? string\n\
---@field listText? string\n\
---@field descriptionTitle? string\n\
---@field descriptionText? string\n\
\n\
---@class (exact) installua.Page.Directory : installua.Page.Headed\n\
---@field subCaption? string\n\
---@field topText? string\n\
---@field destinationText? string\n\
---@field variable? string\n\
---@field verifyOnLeave? boolean\n\
---@field colors? installua.Colors\n\
\n\
-- `registry` is one field holding three because MUI2 reads the three only\n\
-- together: any one of them alone is a define nothing looks at.\n\
---@class (exact) installua.Page.StartMenu : installua.Page.Headed\n\
---@field defaultFolder? string\n\
---@field topText? string\n\
---@field checkbox? boolean|string\n\
---@field registry? { root: string, key: string, value: string }\n\
---@field destroyed? fun()\n\
\n\
---@class (exact) installua.Page.InstFiles : installua.Page.Headed\n\
---@field subCaption? string\n\
---@field finishHeaderText? string\n\
---@field finishHeaderSubText? string\n\
---@field abortHeaderText? string\n\
---@field abortHeaderSubText? string\n\
\n\
-- `run` and `readme` are each a program to start or a function to call, and\n\
-- they are two shapes rather than one with optional members: MUI2 expands the\n\
-- parameters only where there is no function to call.\n\
---@class (exact) installua.Page.Finish : installua.Page\n\
---@field title? string|{ text: string, lines: integer }\n\
---@field text? string|{ text: string, large: boolean }\n\
---@field button? string\n\
---@field cancelEnabled? boolean\n\
---@field reboot? boolean|{ text?: string, now?: string, later?: string, default?: string }\n\
---@field run? { path: string, parameters?: string, text?: string, checked?: boolean }|{ call: fun(), text?: string, checked?: boolean }\n\
---@field readme? { path: string, text?: string, checked?: boolean }|{ call: fun(), text?: string, checked?: boolean }\n\
---@field link? { text: string, url: string, color?: string }\n\
---@field destroyed? fun()\n\
\n\
---@class (exact) installua.Page.Confirm : installua.Page.Headed\n\
---@field subCaption? string\n\
---@field topText? string\n\
---@field locationText? string\n\
---@field variable? string\n\
\n\
---@class (exact) installua.Page.Custom : installua.Page.Headed\n\
---@field [1]? string\n\
---@field controls? table\n\
\n\
-- The one page bound to a local — `local menu = page.startMenu { … }` — because\n\
-- MUI2 names it from install-time code: the folder is read back through the id\n\
-- and the shortcut writing is wrapped in it (§13).\n\
---@class (exact) installua.StartMenu\n\
---@field folder string The folder the page chose. Read-only.\n\
local StartMenu = {}\n\n\
--- Wraps the code that creates the shortcuts, so the chosen folder is written\n\
--- back to the registry. The installer's; the uninstaller reads `folder`.\n\
---@param body fun()\n\
function StartMenu.write(body) end\n\n\
---@class installua.Pages\n\
---@field welcome fun(options?: installua.Page.Welcome)\n\
---@field license fun(options: installua.Page.License)\n\
---@field components fun(options?: installua.Page.Components)\n\
---@field directory fun(options?: installua.Page.Directory)\n\
---@field startMenu fun(options?: installua.Page.StartMenu): installua.StartMenu\n\
---@field instFiles fun(options?: installua.Page.InstFiles)\n\
---@field finish fun(options?: installua.Page.Finish)\n\
---@field confirm fun(options?: installua.Page.Confirm)\n\
---@field custom fun(options?: installua.Page.Custom)\n\
\n\
---@type installua.Pages\n\
page = {}\n\n";

/// The top-level `attributes {}` fields and their Lua types.
///
/// Derived from the census: every `Attribute` row whose field path is a plain
/// name. The nested ones (`versionInfo.product`) are the `VersionInfo` class
/// above, which is why the dot is in the overlay and not in a second list.
fn attribute_fields() -> Vec<(&'static str, String)> {
    table::table()
        .iter()
        .filter_map(|entry| match entry.class {
            Class::Attribute(holds) => Some((entry, entry.installua?, holds)),
            _ => None,
        })
        .filter(|(_, field, _)| !field.contains('.'))
        .map(|(entry, field, holds)| (field, setting_type(entry, field, holds)))
        .chain([("versionInfo", "installua.VersionInfo".to_string())])
        .collect()
}

/// The Lua type of one attribute, which is the row's [`table::Setting`] and
/// nothing else. An enum becomes the alias generated above, which is what makes
/// its members complete rather than merely legal.
///
/// A [`table::Setting::Table`] becomes an inline table type rather than a named
/// class: the parts are the field's own and are named nowhere else, so a class
/// would be a name the user has to learn in order to write a literal they were
/// going to write anyway. Its enum parts are keyed on the *parameter*, matching
/// the alias [`alias_table`] emits for them.
fn setting_type(entry: &table::Instruction, field: &str, holds: table::Setting) -> String {
    let ty = bare_type(entry, field, holds);
    // A repeating position takes a list of one value, the same way a repeating
    // *line* takes a list of one line. That the two spell alike in Lua and
    // differently in NSIS is the point: a caller writes what the field holds
    // and never learns which kind of repetition it is.
    match entry.params.first() {
        Some(param) if param.repeats() => format!("{ty}[]"),
        _ => ty,
    }
}

/// The type of one value of the field, before the snapshot is asked whether the
/// position it stands against repeats.
fn bare_type(entry: &table::Instruction, field: &str, holds: table::Setting) -> String {
    match holds {
        table::Setting::Bool { .. } => "boolean".to_string(),
        table::Setting::Int => "integer".to_string(),
        table::Setting::Enum => alias_of(field),
        table::Setting::Str { .. } => "string".to_string(),
        table::Setting::Handled(ty) => ty.to_string(),
        table::Setting::Table(parts) => inline_table(entry, parts, None),
        // `false` and not `boolean`: `true` is not a value this field takes, and
        // a literal type is the only way to say so where the user reads it.
        table::Setting::Off { parts, least, .. } => {
            format!("false|{}", inline_table(entry, parts, Some(least)))
        }
        // A list of whatever one line takes. The brackets go on the outside
        // because the repetition is of the *line*, which is the whole of what
        // the inner type describes.
        table::Setting::Each(one) => format!("{}[]", bare_type(entry, field, *one)),
        // The type the field has where it is read at all. LuaCATS cannot say
        // "only beside this sibling" — there is no annotation for a constraint
        // between two fields of one table — so the editor offers the name and
        // the compiler is where the pairing is checked. A `---@field` that
        // withheld the type instead would lose completion on the case that
        // works, to describe the case that does not.
        table::Setting::Only { of, .. } => bare_type(entry, field, *of),
    }
}

/// The inline table type a field's parts spell, one key per position.
///
/// `least` is [`table::Setting::Off`]'s, for the reason its lowering reads it:
/// the snapshot flattened the alternation and has one position where the branch
/// has several, so the row is the only thing left that knows.
fn inline_table(
    entry: &table::Instruction,
    parts: &'static [table::Part],
    least: Option<usize>,
) -> String {
    let parts: Vec<String> = parts
        .iter()
        .enumerate()
        .map(|(index, part)| {
            let ty = match (part.holds, least) {
                (table::Setting::Enum, None) => entry
                    .params
                    .get(index)
                    .map(|param| alias_of(param.shape.name))
                    .unwrap_or_else(|| "string".to_string()),
                (other, _) => bare_type(entry, part.field, other),
            };
            let optional = match least {
                Some(least) => index >= least,
                None => entry
                    .params
                    .get(index)
                    .is_some_and(|param| !param.required()),
            };
            format!("{}{}: {ty}", part.field, if optional { "?" } else { "" })
        })
        .collect();
    format!("{{ {} }}", parts.join(", "))
}

fn declarations() -> String {
    let mut out = String::from(
        "--------------------------------------------------------------------------------\n\
         -- Declarations (§15.10). These are language constructs rather than\n\
         -- instructions, so they are written here rather than generated.\n\
         --------------------------------------------------------------------------------\n\n\
         -- §15.23's pair: a short form when there is nothing to configure, and a\n\
         -- table form when there is. The table's array part is the parameters and\n\
         -- its hash part the options, as `file { \"docs/\", recursive = true }` is\n\
         -- `File /r \"docs\\\"`.\n\n\
         ---@class (exact) installua.SectionOptions\n\
         ---@field [1] string The section's name, written first and without a key.\n\
         ---@field body fun() What the section installs.\n\
         ---@field optional? boolean Starts unticked in the components tree.\n\
         ---@field required? boolean Always installed, with no box to untick.\n\
         ---@field installTypes? string[] Which of the block's `installTypes` this belongs to.\n\
         ---@field size? integer Extra kilobytes to charge, beyond the files installed.\n\
         ---@field description? string The words the components page shows on hover.\n\
         local SectionOptions = {}\n\n\
         ---@param name string\n\
         ---@param body fun()\n\
         ---@return installua.Section\n\
         ---@overload fun(options: installua.SectionOptions): installua.Section\n\
         function section(name, body) end\n\n\
         ---@class (exact) installua.GroupOptions\n\
         ---@field [1] string The group's heading, written first and without a key.\n\
         ---@field sections table The sections it holds.\n\
         ---@field expanded? boolean Opens the heading in the components tree.\n\
         ---@field description? string The words the components page shows on hover.\n\
         local GroupOptions = {}\n\n\
         ---@param name string\n\
         ---@param sections table\n\
         ---@return installua.Group\n\
         ---@overload fun(options: installua.GroupOptions): installua.Group\n\
         function group(name, sections) end\n\n\
         -- What a bound `section` is at install time: the handle §13's binding\n\
         -- produces. Every field is readable and writable, and the section index\n\
         -- NSIS reads is the compiler's — it appears in no Installua source.\n\
         ---@class (exact) installua.Selectable\n\
         ---@field selected boolean Ticked in the components tree (`SF_SELECTED`).\n\
         ---@field readOnly boolean Installed with no box to untick (`SF_RO`).\n\
         ---@field bold boolean Drawn bold in the components tree (`SF_BOLD`).\n\
         ---@field text string The row the tree draws; `\"\"` draws none.\n\
         local Selectable = {}\n\n\
         ---@class (exact) installua.Section : installua.Selectable\n\
         ---@field size integer Kilobytes charged beyond the files installed.\n\
         ---@field installTypes string[] Which of the block's `installTypes` it belongs to.\n\
         local Section = {}\n\n\
         -- A group is a section to NSIS — one index, one flags word — plus the\n\
         -- one bit only a heading has, and minus the two only a section has: a\n\
         -- group is charged no space and belongs to no install type, because\n\
         -- what it holds is sections and each of those answers for itself.\n\
         ---@class (exact) installua.Group : installua.Selectable\n\
         ---@field expanded boolean Opens the heading in the components tree (`SF_EXPAND`).\n\
         local Group = {}\n\n\
         -- The install type the user picked, by the name the block declared, and\n\
         -- `\"\"` for the custom one every list has and no list declares (§13).\n\
         ---@type string\n\
         currentInstType = nil\n\n\
         -- The block's install types, addressed by name because an install type\n\
         -- is a line in a block's field and there is nothing to bind (§13).\n\
         ---@class installua.InstTypes\n\
         instTypes = {}\n\n\
         ---@param name string\n\
         ---@param body function\n\
         function func(name, body) end\n\n\
         ---@param body fun()\n\
         function onInit(body) end\n\n\
         -- Source layout, not a module system: the file's declarations are\n\
         -- merged into this one and nothing is emitted (§15.28). The names it\n\
         -- contributes come from `project.lua` beside this file, since\n\
         -- `lua-language-server` cannot follow the merge itself.\n\
         ---@param path string\n\
         function include(path) end\n\n\
         -- The two iterators, and the halves they run in. `glob` is expanded on\n\
         -- the build machine and its loop is unrolled, so the pattern has to be\n\
         -- known there (§7); `lines` runs at install time, over a handle\n\
         -- `fileOpen` returned.\n\
         ---@param pattern string\n\
         ---@return fun(): string\n\
         function glob(pattern) end\n\n\
         ---@param handle installua.File\n\
         ---@return fun(): string\n\
         function lines(handle) end\n\n\
         ---@param header string\n\
         ---@return table\n\
         function import(header) end\n\n\
         ---@param name string\n\
         ---@return table\n\
         function plugin(name) end\n\n\
         ---@param text string\n\
         function raw(text) end\n\n\
         ---@param options string|table\n\
         ---@return string\n\
         function messageBox(options) end\n\n\
         ---@param path string\n\
         ---@param mode installua.OpenMode\n\
         ---@return installua.File\n\
         function fileOpen(path, mode) end\n\n\
         ---@class installua.File\n\
         local File = {}\n\n",
    );
    out.push_str(&file_methods());
    out
}

/// One `function` per `Exposed` row, from the joined table.
///
/// `Out` parameters do not appear in the parameter list: their count **is** the
/// number of Lua return values (§15.23), so a stub that listed them would be
/// teaching the NSIS calling convention this language exists to hide.
/// The control declarations, from the same table that lowers them (§15.32).
///
/// Generated rather than written out, so that a kind added to the table is a
/// kind the editor completes: fifteen near-identical stubs are exactly the
/// thing a list should produce.
fn controls() -> String {
    let mut out = String::from(
        "-- The controls a `page.custom` draws (§15.32), in §15.23's table form: the\n\
         -- array part is the text the control is drawn with and the hash part is\n\
         -- where it sits. A control is listed by a page's `controls`, and the\n\
         -- `local` it is bound to decides nothing about its position.\n\n\
         ---@class (exact) installua.ControlOptions\n\
         ---@field [1]? string The text it is drawn with, where it has one.\n\
         ---@field x? integer|string From the left edge; defaults to 0.\n\
         ---@field y? integer|string From the top. Required: there is no auto-flow.\n\
         ---@field width? integer|string Defaults to the width of the dialog.\n\
         ---@field height? integer|string Required, for the same reason as `y`.\n\
         ---@field items? string[] The rows of a `dropList` or a `listBox`.\n\
         ---@field image? string The `.bmp` a `bitmap` draws.\n\
         ---@field onClick? fun() Called when it is clicked.\n\
         ---@field onChange? fun() Called when what it holds changes.\n\
         ---@field url? string An `onClick` that opens an address.\n\
         local ControlOptions = {}\n\n\
         -- A colour is six hexadecimal digits, in the order Windows writes them.\n\
         -- Both are named because `SetCtlColors` writes both in one instruction.\n\
         ---@class (exact) installua.Colors\n\
         ---@field text string\n\
         ---@field background string Or `\"transparent\"`, to leave it unpainted.\n\
         local Colors = {}\n\n\
         ---@class (exact) installua.Font\n\
         ---@field face string A typeface name; Windows substitutes if it has none.\n\
         ---@field size integer In points, as a word processor would say it.\n\
         ---@field bold? boolean\n\
         local Font = {}\n\n\
         -- What a bound control is at install time. The window handle NSIS reads\n\
         -- is the compiler's: it appears in no Installua source.\n\
         --\n\
         -- Five of the seven fields are write-only, because Windows offers no\n\
         -- instruction that reports them: NSIS can set a control's colours and\n\
         -- cannot ask what they are.\n\
         ---@class (exact) installua.Control\n\
         ---@field value string Its text.\n\
         ---@field checked boolean A `checkbox`'s or a `radioButton`'s tick.\n\
         ---@field enabled boolean Write-only.\n\
         ---@field visible boolean Write-only.\n\
         ---@field colors installua.Colors Write-only.\n\
         ---@field font installua.Font Write-only.\n\
         ---@field image string Write-only; a `bitmap`'s picture.\n\
         local Control = {}\n\n",
    );
    for control in control::CONTROLS {
        let _ = writeln!(
            out,
            "---@param options installua.ControlOptions\n\
             ---@return installua.Control\n\
             function {}(options) end\n",
            control.installua
        );
    }
    out
}

fn instructions() -> String {
    let mut out = String::from(
        "--------------------------------------------------------------------------------\n\
         -- Instructions, one per `Class::Exposed` row (§15.23).\n\
         --------------------------------------------------------------------------------\n\n",
    );

    let mut seen: BTreeSet<&str> = BTreeSet::new();
    for entry in exposed() {
        let Some(name) = entry.installua else {
            continue;
        };
        // A method (`f:read`) belongs to its class above, a field of a section
        // handle (`handle.text`) and `currentInstType` belong to the classes
        // beside it — a `Kind::Bound` position is what says a row is reached
        // through a name rather than called (§13) — and a name that two NSIS
        // rows share (`writeReg` is `WriteRegStr` and `WriteRegDWORD`) is
        // declared once.
        if name.contains(':') || entry.bound() || HAND_SHAPED.contains(&name) || !seen.insert(name)
        {
            continue;
        }

        out.push_str(&declaration(entry, name, name, 0));
    }
    out
}

/// The file handle's methods, from the same rows as everything else.
///
/// `fileOpen` returns a handle and the rest of the file surface is methods on
/// it, which is the one place a row's *first position* is not an argument: NSIS
/// spells it `FileRead handle output` and a user writes `f:read()`, so the
/// handle is the receiver and is dropped from the parameter list here.
///
/// Generated rather than written out, and that is the fix for how this drifted:
/// three of the ten were declared by hand and the other seven — `readByte`,
/// `seek`, the UTF-16 pair and the rest — compiled fine and completed nowhere.
fn file_methods() -> String {
    let mut out = String::new();
    for entry in exposed() {
        let Some(name) = entry.installua else {
            continue;
        };
        let Some(method) = name.strip_prefix("f:") else {
            continue;
        };
        out.push_str(&declaration(entry, name, &format!("File:{method}"), 1));
    }
    out
}

/// One `function`, annotated: the positions, the options table, the returns.
///
/// `skip` is how many leading positions the spelling has already accounted for
/// — one for a method, whose receiver is its first — and the *index* passed to
/// [`union`] is the true one either way, because the type comes from the row.
fn declaration(
    entry: &'static table::Instruction,
    name: &str,
    spelling: &str,
    skip: usize,
) -> String {
    let mut out = String::new();
    // The completion a reader gets is the call they can write, so the two
    // shapes are said apart: an unambiguous trailing optional is a `?`
    // parameter, and everything else optional is a named field below
    // (§15.23).
    let mut names = Vec::new();
    for (index, param) in entry.positional().enumerate().skip(skip) {
        let ident = identifier(param.shape.name);
        let optional = if param.required() { "" } else { "?" };
        let _ = writeln!(out, "---@param {ident}{optional} {}", union(name, index));
        names.push(ident);
    }
    // Both halves of the options table, in one type: the optional positions
    // that are named rather than counted, and the flags, which are mostly
    // `boolean` because the compiler writes the `/FLAG` itself (§15.23).
    let fields = entry
        .fields()
        .map(|(field, param)| format!("{}: {}", field.name, lua_type(param)));
    let options: Vec<String> = fields
        .chain(
            entry
                .flags()
                .filter_map(|(name, flag)| Some(format!("{name}: {}", flag_type(flag)?))),
        )
        .collect();
    if !options.is_empty() {
        let _ = writeln!(out, "---@param options? {{ {} }}", options.join(", "));
        names.push("options".to_string());
    }
    for param in entry.outputs() {
        let _ = writeln!(out, "---@return {}", lua_type(param));
    }
    // A predicate has no output *parameter* — the branch supplies the value
    // — so its return type comes from the builtin rather than from the row
    // (§15.20). The two tables meet here and nowhere else.
    if builtins::lookup(name).is_some_and(|builtin| builtin.predicate) {
        out.push_str("---@return boolean\n");
    }
    let _ = writeln!(out, "function {spelling}({}) end\n", names.join(", "));
    out
}

/// The Lua type of one flag's field. A `bool` for the ordinary flag, whose
/// value is only whether to write it, and a list where the flag repeats
/// (`File`'s `/x`).
///
/// `None` is a flag that is not this table's to describe: `Offer::Handled`
/// belongs to a hand-shaped declaration above, and the other two variants have
/// no name to be reached by at all.
fn flag_type(flag: &table::Flag) -> Option<&'static str> {
    match flag.offer {
        table::Offer::Named(_) => Some("boolean"),
        table::Offer::List { .. } => Some("string[]"),
        table::Offer::Valued { ty, .. } => Some(lua_name(ty)),
        table::Offer::Handled(_) | table::Offer::Always | table::Offer::Unoffered(_) => None,
    }
}

/// Names whose Lua surface is not the NSIS shape, declared by hand above and
/// skipped here.
///
/// Two of them, and both for a reason the parameter model cannot carry:
/// `messageBox` takes a text or a table because §15.18 turned a mode string and
/// a jump table into one value, and `fileOpen` returns the `installua.File`
/// whose methods are the rest of the file surface. Everything else is generated,
/// and a third entry here would be a sign the model is missing a field rather
/// than that the command is special.
const HAND_SHAPED: &[&str] = &["messageBox", "fileOpen"];

fn constants() -> String {
    let mut out = String::from(
        "--------------------------------------------------------------------------------\n\
         -- Predefined NSIS constants, as ordinary read-only globals (§15.1). A `$` in a\n\
         -- literal is an error; these are joined with `..` instead.\n\
         --------------------------------------------------------------------------------\n\n",
    );

    for constant in builtins::CONSTANTS {
        let _ = writeln!(
            out,
            "---@type {}\n{} = nil\n",
            lua_name(constant.ty),
            constant.installua
        );
    }
    out
}

fn exposed() -> impl Iterator<Item = &'static table::Instruction> {
    table::table()
        .iter()
        .filter(|entry| entry.class == Class::Exposed)
}

/// A `-CMDHELP` parameter name is documentation, not an identifier:
/// `shortcut_name.lnk` and `$(user_var: new position output)` both appear.
fn identifier(name: &str) -> String {
    let cleaned: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    match cleaned.chars().next() {
        Some(c) if c.is_ascii_digit() => format!("_{cleaned}"),
        Some(_) => cleaned,
        None => "value".to_string(),
    }
}

/// The type of one input position, over **every** row that shares an Installua
/// name.
///
/// `writeReg` is `WriteRegStr` and `WriteRegDWORD`, and its last argument is a
/// `string` or an `integer` depending on which — that is the dispatch §15.23
/// describes, and taking the first row's type would make the other half of it
/// an editor error on correct code.
fn union(name: &str, index: usize) -> String {
    let mut types: Vec<String> = Vec::new();
    for entry in exposed().filter(|entry| entry.installua == Some(name)) {
        let Some(param) = entry.positional().nth(index) else {
            continue;
        };
        let ty = lua_type(param);
        if !types.contains(&ty) {
            types.push(ty);
        }
    }
    types.join("|")
}

fn lua_type(param: &Param) -> String {
    if param.members().is_empty() {
        lua_name(param.ty).to_string()
    } else {
        alias_of(param.shape.name)
    }
}

fn lua_name(ty: Ty) -> &'static str {
    match ty {
        Ty::Int(_) => "integer",
        Ty::Str => "string",
        Ty::Bool => "boolean",
        // A handle is opaque by construction: it can be passed along and not
        // computed with (§15.14), and `any` is the closest LuaCATS gets to
        // saying so without inviting arithmetic on it.
        Ty::Handle | Ty::Unknown => "any",
    }
}

/// The project meta file §15.28 obliges: every `func` and global the project
/// declares, so completion and go-to-definition survive `include`.
///
/// `lua-language-server` cannot follow `include` — it is frontend-only and
/// leaves no trace in the output — so without this, every name an included file
/// contributes is an unknown global, which is the problem §1 exists to prevent.
/// It is stale until regenerated, which is already the workflow for the stubs
/// beside it.
pub fn project_meta(sources: &[(String, String)]) -> String {
    let mut out = String::from(
        "---@meta\n\
         \n\
         -- Generated by `installua stubs` from this project's own sources.\n\
         --\n\
         -- `include` is frontend-only, so `lua-language-server` cannot follow it and\n\
         -- every name an included file contributes would be an unknown global (§15.28).\n\
         -- Regenerate after adding a `func` or a global.\n\n",
    );

    let mut funcs: Vec<(String, Vec<String>, String)> = Vec::new();
    let mut globals: BTreeSet<String> = BTreeSet::new();

    for (file, source) in sources {
        // A source that does not parse contributes nothing and is not an error
        // here: `installua check` is where a user hears about it, and a stub
        // generator that refused to run because one file is mid-edit would be
        // useless in exactly the editor it exists to serve.
        let mut diags = crate::diag::Diagnostics::new();
        let Some(program) = crate::check(source, &mut diags) else {
            continue;
        };
        let resolved = crate::resolve::resolve(&program, &mut diags);

        for func in resolved.functions.values() {
            let params = func.params.iter().map(|param| param.text.clone()).collect();
            funcs.push((func.name.clone(), params, file.clone()));
        }
        for global in &resolved.globals {
            globals.insert(global.name.clone());
        }
    }

    for (name, params, file) in funcs {
        // The user's own parameter names, because this file is read in hover
        // text and `a1, a2` is worse than nothing there.
        let _ = writeln!(
            out,
            "-- {file}\nfunction {name}({}) end\n",
            params.join(", ")
        );
    }
    for global in globals {
        let _ = writeln!(out, "---@type string\n{global} = nil\n");
    }
    out
}

/// `.installua/installua.yml`: the selene std.
///
/// Two things live here and nowhere else. The stdlib names LuaLS keeps and §5
/// rejects, each `deprecated` with the replacement — `deprecated = "deny"` in
/// `selene.toml` is what makes "every rejection names its replacement" a lint
/// rather than a docs page. And the API's arities, which selene checks and
/// LuaCATS does not enforce on a `table` argument.
pub fn selene_std() -> String {
    let mut out = String::from(
        "# Generated by `installua stubs`. Do not edit.\n\
         #\n\
         # No `base:`: inheriting `lua54` would re-admit every name §5 rejects, and the\n\
         # rejections are the point. What is listed is what exists.\n\
         lua_versions:\n  - lua54\n\
         name: installua\n\
         globals:\n",
    );

    for (name, message, replace) in REJECTED {
        let _ = writeln!(out, "  {name}:\n    args:\n      - type: any");
        let _ = writeln!(out, "    deprecated:\n      message: '{message}'");
        if !replace.is_empty() {
            let _ = writeln!(out, "      replace:\n        - '{replace}'");
        }
    }

    // Every retired NSIS instruction, from the same table the diagnostic reads
    // (§5). A user who types `strCmp` gets the answer at lint time as well as
    // at compile time, with the same text.
    for row in crate::retired::all() {
        let _ = writeln!(
            out,
            "  {}:\n    args:\n      - type: any\n    deprecated:\n      message: 'write {}'",
            row.installua,
            escape(row.instead)
        );
    }

    for entry in exposed() {
        let Some(name) = entry.installua else {
            continue;
        };
        if name.contains(':') || entry.bound() {
            continue;
        }
        let _ = writeln!(out, "  {name}:\n    args:");
        for param in entry.positional() {
            let _ = writeln!(out, "      - type: {}", selene_type(param));
            if !param.required() {
                let _ = writeln!(out, "        required: false");
            }
        }
        // One trailing table for the named half — optional positions, flags, or
        // both — or none at all. A `selene` argument list is positional, so this
        // is as much as it can say; the field names are the language server's
        // job.
        if entry.takes_options() {
            let _ = writeln!(out, "      - type: table\n        required: false");
        }
    }

    // A `Kind::Bound` row is reached through a name rather than called (§13).
    // The dotted ones are fields of a handle and a `local`'s fields are
    // selene's business anyway; `currentInstType` is a global, and one that is
    // written as well as read — `SetCurInstType` is the assignment.
    let mut named: BTreeSet<&str> = BTreeSet::new();
    for entry in exposed().filter(|entry| entry.bound()) {
        let Some(name) = entry.installua else {
            continue;
        };
        if name.contains('.') || !named.insert(name) {
            continue;
        }
        let _ = writeln!(out, "  {name}:\n    property: full-write");
    }

    for constant in builtins::CONSTANTS {
        let _ = writeln!(out, "  {}:\n    property: read-only", constant.installua);
    }
    out
}

/// The names `lua-language-server` keeps and §5 rejects. Each names its
/// replacement, because a lint that only says no is a lint people disable.
const REJECTED: &[(&str, &str, &str)] = &[
    (
        "require",
        "use `include` for source, `import` for NSIS headers (§15.28)",
        "include(%1)",
    ),
    (
        "pcall",
        "NSIS has no exceptions; check `errors()` instead",
        "errors()",
    ),
    (
        "print",
        "the installer log is `detailPrint`",
        "detailPrint(%1)",
    ),
    (
        "pairs",
        "there is no runtime heap; iterate a directory with `glob`",
        "",
    ),
    (
        "ipairs",
        "there is no runtime heap; iterate a directory with `glob`",
        "",
    ),
    ("setmetatable", "there are no metatables", ""),
    (
        "math.floor",
        "there are no floats; `//` is already integer division",
        "%1",
    ),
    ("string.gsub", "Lua patterns have no NSIS lowering", ""),
    ("string.gmatch", "Lua patterns have no NSIS lowering", ""),
];

fn selene_type(param: &Param) -> &'static str {
    match param.ty {
        Ty::Int(_) => "number",
        Ty::Str => "string",
        Ty::Bool => "bool",
        _ => "any",
    }
}

fn escape(text: &str) -> String {
    text.replace('\'', "''")
}

/// `.luarc.json`, written by `installua init`.
///
/// `runtime.builtin: disable` on the libraries §5 rejects wholesale turns
/// `require` and `coroutine.wrap` back into unknown globals for free, rather
/// than needing a rejection list — and `lowercase-global` is off because the
/// API *is* lowercase globals (§15.13).
pub fn luarc() -> String {
    String::from(
        "{\n  \
         \"$schema\": \"https://raw.githubusercontent.com/LuaLS/vscode-lua/master/setting/schema.json\",\n  \
         \"runtime.version\": \"Lua 5.4\",\n  \
         \"runtime.builtin\": {\n    \
         \"coroutine\": \"disable\",\n    \
         \"debug\": \"disable\",\n    \
         \"io\": \"disable\",\n    \
         \"os\": \"disable\",\n    \
         \"package\": \"disable\"\n  \
         },\n  \
         \"workspace.library\": [\".installua/meta\"],\n  \
         \"diagnostics.disable\": [\"lowercase-global\"],\n  \
         \"diagnostics.globals\": []\n\
         }\n",
    )
}

/// `installua.toml`: the project marker, and the one file a user has to know
/// about (§15.13).
pub fn project_toml(name: &str) -> String {
    format!(
        "# The project marker. Its *presence* is what makes this directory an\n\
         # Installua project: `installua init` writes the editor configuration beside\n\
         # it, and the generated stubs apply to this directory and no other (§15.13).\n\
         [project]\n\
         name = \"{name}\"\n\
         entry = \"install.lua\"\n"
    )
}

/// `selene.toml`. `deprecated = \"deny\"` is not decoration: it is what makes
/// the generated std's replacement text a failure rather than advice (§14).
pub fn selene_toml() -> String {
    String::from(
        "std = \"installua\"\n\n\
         # §14: warnings are failures. `deprecated` is how the generated std names a\n\
         # replacement for every §5 rejection, so it must not be advisory.\n\
         [lints]\n\
         deprecated = \"deny\"\n",
    )
}
